### ISSUE TITLE
Geburtsdatum Anzeigeformat

### ISSUE THREAD

**Issue by livingmydesign** [livingmydesign/hdstories#100]
auf DD.MM.YYYY in der Vorschau oben ändern.

**Comment by livingmydesign** [comment]
gelöst @jansthh

**Comment by jansthh** [comment]
Detail und unkritisch, aber jetzt wirkt es unstimmig, wenn darunter die Eingabe immer noch JAHR-MONAT-TAG ist

Können ja erstmal das Feedback abwarten der Spender 🙏🏻
