### ISSUE TITLE
Ladescreen Bug

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#101]
- Gerade klappt fast alles. Teste Kreuz und quer auf iPhone, iPad, Mac. Für mich, für andere, letzte Story 👌🏻

- Bei den Ladescreens stimmt was noch nicht

- Nach dem ersten „mit Samthandschuhen aus dem Archiv“ kommt gleich „Jan spricht Audio ein“ und es fehlt „Team hat Chart inspiziert"

- zudem springt er nach der Fertigstellung zum Screen im Anhang, steht auf 100%, wechselt aber nicht zur Story (obwohl die erstellt und per Mail zugeschickt wurde)

- von dort gelange ich als User nicht mehr zu meiner Story 

![image](https://github.com/livingmydesign/hdstories/assets/159889907/c6e8ab8a-ff8a-4f1c-963e-ecf41464354c)

**Comment by livingmydesign** [comment]
sollte erledigt sein.
