### ISSUE TITLE
Stripe Test

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#103]
@livingmydesign  Habe doch nochmal mit Stripe herumgespielt, weil mich der 1,- bei copecart pro Transaktion schon stört. Donnerstag habe ich einen Call mit Pathway, ein Anbieter für die buchhalterische Anbindung von Stripe an Datev. Hoffe, die können mir helfen.

Für einen Test bitte mit Make.com verbinden. Einladung zum Stripe Admin ist raus wie besprochen.

Das ist der aktuelle Payment Link: https://buy.hdstories.app/b/00gcND0JYcVIg7e4gi (kann sich nochmal ändern, weil bei einer Preisänderung bzw. Steuereinstellung des Preises jedes Mal ein neuer Link angelegt werden muss)

**Comment by livingmydesign** [comment]
scheint gelöst zu sein.
