### ISSUE TITLE
Feedback Fragebogen

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#104]
- Ich habe einen Fragebogen erstellt
- bitte gern mal gegenlesen und deine Meinung äußern
- wir auf Telegram geschrieben, verlinken wir den Fragebogen doch nicht mehr in der App

https://forms.gle/k8uQVz8fovyQxkoc7

**Comment by livingmydesign** [comment]
@jansthh dazu noch feedback von mir:

aktuell sind alle Fragen untereinander.
wenn man sie in sektionen gliedert, könnte man einen fortschrittbalken sehen nach jeder abgeschlossenen sektion.

zu dieser Frage:
Wie angemessen findest du den Preis in Höhe von 2,- Euro für einen Sterntaler? Skala von zu teuer (1) bis sehr angemessen (5)

=> warum nicht am oberen ende: "würde sogar mehr dafür zahlen"
-> schade, dass man in google forms keine conditional-logic fragen wie in monday-forms einbauen kann.
--> dann könnte man hier bei sehr angemessen/unterbewertet/würde mehr dafür zahlen eine folge-frage einfügen, die dann fragt: "wieviel pro personalisierter human design story würdest du bereit sein zu zahlen: 2€ 3€ 4€ 5€"
==> wenn das für dich so interessant wäre, würde ich das formular entsprechend mit monday-forms und conditional logic neu für dich bauen morgen früh bevor wirs rausschicken.

===

Hast du gleich mehrere Sterntaler gekauft? Falls nicht, warum nicht? 
=> die frage muss korrigiert werden. aktuell MUSS man ja mehrere kaufen.

===

Ah ok, am Ende fragst du nochmal nach, was man bereit wäre zu zahlen.
ja, wie gesagt, wenn diese Frage an die Preis-Bewertung am Anfang geknüpft wäre, würden nur jene gefragt werden, die den aktuellen Preis als sehr günstig oder so bewerten. 

wäre denke ich wichtig zu wissen für uns mit offenem ego, den preis so zu platzieren, dass es nicht zu teuer für die breite masse und nicht zu günstig für sagen wir 30% ist, die auch doppelt so viel dafür zahlen würden, oder.

aber ja - gefühlt ist für mich Taler-gegen-Münze immer noch am stimmigsten mit der strategie, die Kosten auf maximal 1 € pro story belaufen zu lassen sodass wir immer noch 50% gewinn machen.

**Comment by livingmydesign** [comment]
ach was, um uns Zeit zu sparen für dich das zu entscheiden, hab ich es einfach mal schnell nachgebaut und dir auch Zugriff via Monday gegeben:

https://wkf.ms/43mEmvf

spür einfach rein, ob sich diese Form besser anfühlen würde für diese Umfrage.

**Comment by livingmydesign** [comment]
Dann auch noch die Frage, ob Email unbendigt "required" sein soll, wenn die Umfrage ja eh an unsere Freunde geht :)

**Comment by jansthh** [comment]
Großartig!!!! Danke. 

Können/wollen wir nicht auch alles andere in so einem Tool wie Monday abbilden? Entwicklung, Marketing etc. - alles an einem Ort?

Lass uns gern den Fragebogen dort verwenden. E-Mails würde ich dann freiwillig angeben. Aber den Fragenbogen schicken wir sicher auch nochmal an andere.

PS: Habe den Link von oben auch im Sendgrid Donor Template ausgetauscht

**Comment by livingmydesign** [comment]
Alles klar - Done.

@jansthh erstmal nur der Fragebogen.

vielleicht auch alles andere - quatschen wir noch.
