### ISSUE TITLE
Blitzer als letzter Screen vor My Story Seite

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#105]
- bei jeder Story Erstellung blitzt zwischen dem letzten 100% Ladescreen und der mystory Seite nochmal für einen Sekundenbruchteil die Story-Stil-Auswahl-Seite auf (zB Alice im Wunderland), bevor die erstellte Story final erscheint

vielleicht hilft es, wenn ich dich nochmal erwähne @livingmydesign

**Comment by livingmydesign** [comment]
bin mir dessen bewusst und weiß noch nicht, wie sich das technisch lösen lässt in der aktuellen umsetzung mit make. mal sehen, vielleicht fällt mir dazu noch etwas ein. @jansthh

**Comment by livingmydesign** [comment]
sollte nun behoben sein. @jansthh
