### ISSUE TITLE
Neue Github Issues erstellen

### ISSUE THREAD

**Issue by livingmydesign** [livingmydesign/hdstories#106]
Lieber @Jansthh, leider sehe ich hier keine neuen Issues von dir.

Warum?

Hast du auch immer auf den "Submit new Issue"-Button unten geklickt nach dem Schreiben?

**Comment by jansthh** [comment]
ich antworte nochmal auf dieses Issue. In der Hoffnung, dass es was bringt.

ja, habe ich. Und ich weiß auch nicht, warum du sie nicht siehst. :/

**Comment by livingmydesign** [comment]
solved. @jansthh
