### ISSUE TITLE
Menu Link fkt. nicht (GitHub Issue Test)

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#107]
@livingmydesign Ich dachte, ich probiere es einfach nochmal:

- der Menu Link fkt. gerade nicht auf dem Desktop (sprint nach Klick einfach zum Home Screen)
- auf der mystory Seite erscheint er außerdem gar nicht erst (siehe Screenshot)

- wie kann ich diesen Inhalt eigentlich in FF anpassen, wenn ich einen Punkt ergänzen möchte zB bei den FAQs? Ohne, was kaputt zu machen ;)

![Bildschirmfoto 2024-03-19 um 09 08 39](https://github.com/livingmydesign/hdstories/assets/159889907/cfda81e2-8026-407a-9077-3741e67ff3ac)

**Comment by jansthh** [comment]
Aktuell fkt. er wieder – manchmal fkt. Elemente nicht immer oder gleich, wenn man die App neu deployed – und dann wieder, wenn man nochmal deployed

Magst du den Footer auch auf der Library Seite unten einblenden? So dass man man immer und überall Zugriff auf den Menu Button hat

**Comment by livingmydesign** [comment]
Menü in den myStories war bisher so eingestellt, dass es nur bestehende (eingeloggte) User sehen könnten.
Mit dem Gedanken, dass innerhalb des Menüs Member-Only-Content kommt.

hab es jetzt mal komplett geöffnet. denke, es ist ok so

@jansthh

**Comment by livingmydesign** [comment]
done.
