### ISSUE TITLE
Donors Inbox

### ISSUE THREAD

**Issue by livingmydesign** [livingmydesign/hdstories#108]
<img width="521" alt="Screenshot 2024-03-20 at 07 37 51" src="https://github.com/livingmydesign/hdstories/assets/93006467/d47f0e85-f194-48f8-8ac5-3c4ab89af408">

das sehen die donors als erstes sobald sie ihre 1te von 2 stories eingelöst haben, oder (wie hier) nach der eingabe der geburtsdaten nochmal auf den link klicken.

bitte entsprechend einen anderen Text an mich durchgeben zum Austauschen.

**Comment by livingmydesign** [comment]
Ach ja: Ich kann leider keinen Trial für Donors aktivieren - Sprich, sie kriegen gleich 2 Credits.

-> entsprechend kann auch im Fragebogen dann diese eine Frage entfallen.

**Comment by jansthh** [comment]
Ich habe noch nicht herausgefunden, wie ich den Feedback-Fragebogen in Monday anpassen kann. Magst du dann das E-Mail Feld auf frewillig stellen und die Frage zur Gratis/Premium Story entfernen?

Habe das E-Mail Template angepasst mit dem Hinweis auf 2 Sterntaler.

Text für den Donor-App-Screen:

"Wir sind so dankbar für deinen Support und deine Geduld. Löse nun deine Geschenke ein und nutze die beiden Sterntaler, um zwei Premium Stories für dich oder deine Liebsten erstellen zu lassen. Viel Freude, dein Jan."

**Comment by livingmydesign** [comment]
@jansthh 

Monday: ist angepasst. 

Text: ist ausgetauscht zu: 
"Wir sind so dankbar für deinen Support und deine Geduld. Löse nun deine Geschenk ein und nutze deinen Sterntaler, um eine Premium Story für dich oder deine Liebsten erstellen zu lassen. Viel Freude, dein Jan."
Hintergrund: In die Inbox kommt man als Donor erst, wenn man bereits die erste kostenfreie Story erstellt hat und dann noch eine zaubert.
