### ISSUE TITLE
Donor Story Test

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#112]
- habe mit @googlemail.com eine Donor Story erstellt
- hat alles super geklappt
- Story wurde erstellt
- dann wollte ich auf neue Story zaubern gehen
- werde weitergeleitet und sehe oben auch "1 Sterntaler" Guthaben

- und dann kam ein Fehler: er springt die ganze Zeit zwischen inbox und data hin und her (siehe Video)
- konnte das nur unterbrechen mit der Eingabe von hdstories.app home Seite im Browser

- von der Startseite wüsste ich dann nicht, wie ich zurück käme 
-> brauchen wir hier nicht noch irgendwie nen Text wie "Schon eingeloggt? Klicke hier."
- damit der User mit Guthaben wieder zur Story Erstellung kann (für ihn oder für andere)

https://github.com/livingmydesign/hdstories/assets/159889907/91c13e03-fa66-471d-b8cb-2258a3a3f4ce

**Comment by livingmydesign** [comment]
merci, kümmere mich morgen um den loop. @jansthh 
dürfte schnell behoben sein.

**Comment by livingmydesign** [comment]
Die Startseite sollte erstmal nirgends verlinkt sein für die Donors-Phase.

Donors haben ihren Link in der Email um reinzukommen.

**Comment by jansthh** [comment]
Alles klar. Sprich, wenn sie nach dem ersten Login wieder reinwollen, müssen sie einfach nochmal auf den Link in der Mail klicken?

**Comment by livingmydesign** [comment]
korrekt.

Bis zum offiziellen Launch.

**Comment by livingmydesign** [comment]
@jansthh auch dieser (umfänglicher als gedachte) Bug sollte nun behoben sein.
Erste Tests waren erfolgreich.
