### ISSUE TITLE
Email Zahlungslinks zu Stripe ändern

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#113]
- habe eben meine Mail zur Donor Test Story erhalten
- zum Test auf den Story kaufen Button geklickt 
- da kam noch CopeCart
- das sind ja diese dynamischen Links: {{ insert story_order 'default=default' }}
- magst du das bitte noch zu Stripe ändern?
- Ich deaktiviere das CopeCart Produkt, so dass keine versehentlichen Käufe getätigt werden können

![image](https://github.com/livingmydesign/hdstories/assets/159889907/6c32bfe9-668a-4c5b-bff9-1584ec37bebd)

**Comment by livingmydesign** [comment]
solved. @jansthh
