### ISSUE TITLE
Footer Menu Library unsichtbar

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#114]
- Danke fürs Einfügen des Footer Menus in der Library
- kann es sein, dass du die helle Version (die auch auf dunklen Hintergründen steht) aktivierst hast?
- siehe Screenshot

![image](https://github.com/livingmydesign/hdstories/assets/159889907/f43aa558-d292-4538-a5a5-fe0efd139ea5)

**Comment by livingmydesign** [comment]
solved. @jansthh
