### ISSUE TITLE
Falscher Link in Donor-Kunden Mail

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#116]
- die Kundin Manja (manjakuehn@gmx.de) konnte ihre erste Story nicht downloaden (siehe Screenshot)
- habe ihr erstmal einen Credit geschenkt (super Funktion!)
- kannst du das nachvollziehen und können wir ihr den Link zum korrekten Audio zukommen lassen?
- diese Story wird auch im Dashboard nicht angezeigt 

![image](https://github.com/livingmydesign/hdstories/assets/159889907/5d086420-25a9-4f61-9c7d-d696eb742275)

**Comment by livingmydesign** [comment]
Das Link-Thema ist behoben, siehe: https://github.com/livingmydesign/hdstories/issues/117

hier alle 3 Manja Stories:
https://hdstories.app/mystory/623b30
https://hdstories.app/mystory/623b300d
https://hdstories.app/mystory/EaLawO

**Comment by livingmydesign** [comment]
closed. @jansthh

**Comment by jansthh** [comment]
Danke dir. Per Link hören konnte sie die Story auch. 

Kann sie die erste erstellte Story (unendliche Geschichte) auch irgendwie downloaden? 

Sprich, ist der Download Link in der Mail jetzt auch korrekt? Wurde ja von der 2. Geschichte überschrieben

Wenn das nicht geht, mache ich das einmal manuell und schicke es dir, kein Ding 🙏🏻

**Comment by livingmydesign** [comment]
@jansthh bitte einmal ihr zuschicken.

der link in den emails war einmal falsch
