### ISSUE TITLE
StIDs wurden mehrfach erzeugt und nicht befüllt: janine knops

### ISSUE THREAD

**Issue by livingmydesign** [livingmydesign/hdstories#118]
![Screenshot 2024-03-24 at 03 26 11](https://github.com/livingmydesign/hdstories/assets/93006467/1094c730-3d71-4b63-93a4-325353374784)
![Screenshot 2024-03-24 at 03 25 27](https://github.com/livingmydesign/hdstories/assets/93006467/c203adec-f78a-4c91-926e-ccd10f47f546)

To Research & Fix:
- [x] Wie war es möglich mehrere StIDs zu erzeugen? mehrfach zwischen Library & Inbox wechseln?
- [x] Wenn bereits eine leere StID vorhanden ist, sollte keine neue angelegt werden

**Comment by livingmydesign** [comment]
Failsafe eingebaut in make.com
wurden erzeugt, wenn zwischen library und inbox hin und her gewechselt wurde.
@jansthh

**Comment by jansthh** [comment]
sehr gut – wir müssen vor allem davon ausgehen, dass die User ständig hin und her springen im Browser (zurück und vor Tasten). Ein paar Dinge haben wir ja schon in der Entwicklung eingebaut beim Namen und letzte Story etc. 

aber da müssen wir sicher auch noch einiges lernen
