### ISSUE TITLE
Backup-Pfad war nicht ausreichend: STID wäre 3mal überschrieben worden: MR

### ISSUE THREAD

**Issue by livingmydesign** [livingmydesign/hdstories#119]
![Screenshot 2024-03-24 at 03 34 58](https://github.com/livingmydesign/hdstories/assets/93006467/c5138747-25bf-44f6-9940-270970805ab1)
![Screenshot 2024-03-24 at 03 34 07](https://github.com/livingmydesign/hdstories/assets/93006467/e2f915a4-6390-4f0c-bee6-e3c95c2e7c57)
![Screenshot 2024-03-24 at 03 37 41](https://github.com/livingmydesign/hdstories/assets/93006467/3a2c09c0-2ffc-4cbd-be4a-b4b1278d88a3)

uid: 19554156-80de-4afe-8ef7-f034892e3bab

To Research & Fix:
- [x] Wie konnten beinahe 3 Stories erstellt werden obwohl es nur 2 Credits gab? Geschenkt von @jansthh ?
- [x] ShID Erstellung optimieren

**Comment by jansthh** [comment]
FYI: habe MR keinen Coin geschenkt

**Comment by livingmydesign** [comment]
Failsafe direkt in make.com eingebaut. 
künftig sind keine Stories ohne neuer StID mehr möglich.
