### ISSUE TITLE
Nach Storykauf Bug Eva

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#121]
-Eva.ozean@gmx.de hat weitere Sterntaler gekauft 
- ihr Feedback um 9:43 Uhr heute: "Good Morning, ich hab Sterntaler :)

Allerdings es jetzt 2x nicht geklappt, die Story für meine Mum zu erstellen.

Ich gebe alles ein und nach dem Story erstellen Button kommt diese Ansicht und es geht keine 2-5 min Erstellung los."

- habe eben nachgefragt: "…Ist immer noch so. Komisch"

![image](https://github.com/livingmydesign/hdstories/assets/159889907/ab3f4a15-3783-4c44-a9e8-2e29d02fbfe4)

**Comment by jansthh** [comment]
- Scheint ein generelles Problem gerade zu sein bei der Erstellung - auch ohne Kauf. Hier nochmal Same same von Natascha

- konnte es auch gerade nachstellen bei mir. Nach der Stil Auswahl komme ich zurück zur Inbox (https://hdstories.app/inbox?neuInit=true)

- sowohl bei Story für mich als auch bei Story für jmd. anderen

Hoffe, das hilft. Lasse dich jetzt erstmal machen 🙏🏻

![image](https://github.com/livingmydesign/hdstories/assets/159889907/dbc3eed7-a36a-4d94-a0d0-5eed7bb5911e)

**Comment by livingmydesign** [comment]
@jansthh sollte nun behoben sein.
