### ISSUE TITLE
Shari + Nicole anderer Name

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#124]
- Shari Wenzel hatte ihren Namen falsch eingegeben und kann ihn nun nicht mehr ändern (siehe Screenshots)
- sichtbar und hörbar in ihrer 1. Story: https://hdstories.app/mystory/e2d0da
- kannst du den Namen in "Shari" ändern?
- habe ihr einen Credit geschenkt und sie gebeten, sich bis zur Änderung zu gedulden 

- und perspektivisch sollten wir den Usern die Möglichkeit bieten, ihren eigenen Namen nochmal ändern zu können? Vielleicht dann erst, wenn es User Profile gibt

![image](https://github.com/livingmydesign/hdstories/assets/159889907/6d4de631-e3bd-45de-bd9e-8ed87c3abdb4)

![image](https://github.com/livingmydesign/hdstories/assets/159889907/23f7e44f-ad44-455f-9f14-1b1c14573c1c)

**Comment by jansthh** [comment]
- Same für Nicole Künzler. Nur anders. 
- sie hat "Nic" als Namen angegeben, was GPT als Mann interpretiert hat
- magst du den Namen bitte in "Nicole" ändern? 🙏🏻
- hier die Story dazu: https://hdstories.app/mystory/4YtUnw

![image](https://github.com/livingmydesign/hdstories/assets/159889907/57a848e0-4f09-48f9-baa1-fdc49657920c)

**Comment by jansthh** [comment]
Vielleicht kannst du mir auch zeigen, wonach den Namen ändern kann. Wahrscheinlich in der Firebase Datenbank. Dann kann ich das auch selber machen 🙏🏻😌

**Comment by livingmydesign** [comment]
done.

hier die Anleitung:
![Screenshot 2024-03-25 at 07 08 26](https://github.com/livingmydesign/hdstories/assets/93006467/620190b9-c551-44a0-9a29-9260dc612293)

**Comment by jansthh** [comment]
Klasse, ich danke dir! :)
