### ISSUE TITLE
Weitere Ko-Fi Spender

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#125]
- es sind noch ein paar Spender dazu gekommen seit gestern
- magst du denen auch noch die Mail zuschicken bzw. könnte man das ab jetzt automatisieren, dass sie gleich ihre 2 gratis Stories bekommen?
- zumindest solange, wie wir noch Spenden annehmen

**Comment by livingmydesign** [comment]
@jansthh done - läuft jetzt alle 2h erstmal.

**Comment by jansthh** [comment]
Können wir den Intervall verkürzen? Rufe jetzt öfter dazu auf "Support & Create" - auch auf meiner Website.

Dann sind die nicht irritiert, wenn das 2 Std dauert, bis die Mail kommt 🙏🏻

**Comment by livingmydesign** [comment]
@jansthh auf 60min runter gestellt.
