### ISSUE TITLE
Gender Auswahl

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#127]
- wollen wir eine Gender Auswahl nach dem Namen hinzufügen, damit die AI nicht mehr raten muss?
- 2 Bsp im Anhang

![Bildschirmfoto 2024-03-25 um 15 13 05](https://github.com/livingmydesign/hdstories/assets/159889907/1c50bb34-9a8a-42c0-9016-2cbcc2b66c1b)

![Bildschirmfoto 2024-03-25 um 15 21 04](https://github.com/livingmydesign/hdstories/assets/159889907/95208359-07df-40a2-9014-5689956def90)

**Comment by livingmydesign** [comment]
na zum Glück sind wir deutschen bei dem Thema noch nicht so verrückt wie in den USA....... 
@jansthh

**Comment by jansthh** [comment]
@livingmydesign Ich habe einen weiteren Fall, wo das echt helfen würde und ich jetzt auch nicht wüsste, wie sie für ihre Tochter eine korrekte Story erstellen lassen könnte. In diesem Ausnahmefall nehme ich mal den Text, schreibe ihn um und schicke ihr das 11labs Audio neu zu:

Stephanie
s.mayer82@web.de
https://hdstories.app/mystory/orssU7

"Hallo Jan,

ich nochmal. Ist es möglich, die männliche Form hier auszutauschen? Talvi ist meine Tochter. Hier wird jedoch über einen Jungen mitbihrem Namen gesprochen.
Danke Dir.
Liebe Grüße Stephanie"

**Comment by jansthh** [comment]
Noch eine Idee von einem User:

"Geil wäre noch, wenn man das Geschlecht auf nichtbinär setzen könnte. Nonbinary, ohne Pronomen." -> statt er/sie etc. Würde immer nur der Name genannt werden

**Comment by livingmydesign** [comment]
hum. 

Gerade kein Hell Ya zu diesem neumodischen Trends hier :D

**Comment by livingmydesign** [comment]
aber ja - generell darf das irgendwie rein in den public release.
gpt macht ne vorauswahl eines m/w-symbols, du klickst drauf um es zu ändern.

**Comment by jansthh** [comment]
Habe jetzt mehrere weitere Rückfragen dazu erhalten. Die letzte ist besonders tricky, weil die Tochter Kim heißt, weil der Name ja für beide Geschlechter fkt. - GPT deutet ihn aber männlich.

Ich vertröste die Kundin dann auf den Launch bzw. dass das Feature zukünftig kommt, korrekt? 

Bis dahin bleibt mir ja nur, den Text notfalls manuell für nachfragende Kunden umzuschreiben und in 11labs zu schieben, richtig?

**Comment by livingmydesign** [comment]
Ja, richtigm.. Ist im vergünstigten Beta-Paket aktuell inbegriffen.

**Comment by jansthh** [comment]
Hatte heute eine weitere Kundin (mit 10K Account), die ganz begeistert ist und eine Story einer Business Kundin schenken wollte, der Name aber männlich interpretiert wurde. 

Ist mittlerweile neben einer Individualisierung der Story das meist nachgefragte Feature. Und würde uns auch sehr viele Nachfragen und Probleme ersparen zukünftig.

Also wenn es irgendwie möglich ist, es zum Launch zu implementieren, dann hat es mittlerweile High Prio😌🙏🏻

**Comment by livingmydesign** [comment]
ist jetzt in der ersten Fassung so eingebaut. Sobald man einen Namen eingibt und 2 Sekunden wartet, oder auf "Weiter" klickt, erkennt die KI (GPT 3.5) ein Geschlecht. Mit Klick auf den Button neben dem Namen kann man dann nochmal wechseln. Sollte imho so ausreichend sein. Kein Extra-Klick für John's oder Stefan's oder Jasmina's.

<img width="404" alt="Screenshot 2024-04-15 at 04 41 24" src="https://github.com/livingmydesign/hdstories/assets/93006467/7bc8eada-0bcf-45ea-aa14-f9997d148a28">
@jansthh

**Comment by livingmydesign** [comment]
ach ja: es steht dan "ihr" oder "sein", je nachdem ob m oder w
