### ISSUE TITLE
MK Namensänderung klappt nicht

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#128]
- der User MK engelx22200@yahoo.de bekommt immer wieder nur MK als Name angezeigt in der App und wenn sie Stories für sich erstellt (siehe Screenshot)
- das, obwohl der Name offensichtlich in der Datenbank geändert ist (siehe Screenshot)
- nur, wenn sie eine ganz neue Story erstellt, kann sie logischerweise ihren korrekten Namen Monika eingeben
- ich bat sie, per Link von einer erstellten Story oder hdstories/inbox in die App zu gelangen und nicht über den Donor Einladung Link 
- auch das half nicht 
- bei Ko Fi hat sie ihren Namen wohl auch schon geändert;)

Was können wir tun?

![image](https://github.com/livingmydesign/hdstories/assets/159889907/d2ab662c-4da1-4bbb-9d9f-03aa66d8d693)

![image](https://github.com/livingmydesign/hdstories/assets/159889907/259541ff-b1ca-4fa0-91cc-1360788f6813)

**Comment by livingmydesign** [comment]
dann kanns nur noch der cache sein..

**Comment by jansthh** [comment]
Okay, habe sie gebeten, das zu tun.

Was macht sie danach? Auf den Link in der Donor Mail klicken? Wird dann ihr bei Ko Fi geänderter Name neu gefetched? Oder erstellt er dann wieder MR als Name? Weil sie sich nach dem Cache löschen ja neu anmelden muss und anders nicht reinkommt, korrekt?

**Comment by livingmydesign** [comment]
@jansthh Ja, auf den Link in der Email. Ihr Name ist in der DB ja bereits korrigiert.

**Comment by jansthh** [comment]
@livingmydesign 

Also, die Kundin hat immer noch Probleme. Können wir ihr irgendwie einen neuen Account einrichten? 

"Hi Jan, 

ich habe gerade ausprobiert den letzten Link, den du mir geschickt hattest über zwei andere Browser zu öffnen. Leider ist mir da gar nichts angezeigt worden.

Daher habe ich die Links zu meinen bisher erstellten Storys genutzt. Dabei ist mir wundersamerweise in den zwei anderen Browsern eine neue Story erschienen (auch mit MR). 
Nutzen standardmäßig Ecosia und über Google und über Bing kam jeweils die ganz neue Story. 

![Screenshot_20240326_233203_Chrome](https://github.com/livingmydesign/hdstories/assets/159889907/1c1fc241-dcd4-4e86-8130-7bb589155180)


Ich habe auch nochmal den ursprünglichen Link aus der ersten Einladungsmail benutzt, aber der ist nun ungültig:

![Screenshot_20240326_232642_Chrome](https://github.com/livingmydesign/hdstories/assets/159889907/3318c2b8-7087-4bd7-a566-a92b47a53514)


Ich hatte gedacht, ich kann über meine zuletzt erstellten Storys neue Sterntaler kaufen und dann schauen, ob mein Name nun passt bzw.einfach wieder über die andere Funktion neue Storys erstellen. 
Aber nun habe ich noch keine Bestätigung für meine Sterntaler bekommen. Wenn du es erst manuell bestätigen musst, kein Problem. War nur verwundert, weil es letztes Mal direkt ging. 

Ich hoffe, du kannst mir bei den Sterntalern helfen? 
Würde mich freuen, wenn ich noch ein paar Storys erstellen kann. 

Liebe Grüße
Monika"

"Nur noch ein kurzer Nachtrag:
Über meinen Standardbrowser kann ich jetzt wieder neue Storys erstellen, wenn auch als "MR". 
Schätze, in den anderen Browsern fehlt mir jetzt ein bestimmter Cookie oder so, weshalb mein Account nicht erkannt wird. 
Aber halb so wild, Hauptsache es klappt mit dem Erstellen. ;) "

**Comment by livingmydesign** [comment]
@jansthh Ok, Quickfix macht keinen Sinn.
Hab jetzt dazu mal ein kleines erstes Einstellungen-Menü gebaut in der Inbox **oben rechts.**
![Screenshot 2024-03-28 at 08 07 04](https://github.com/livingmydesign/hdstories/assets/93006467/57db7508-8761-430b-a902-fbee1bd97ff4)

somit sollte das Problem behoben sein.

**Comment by jansthh** [comment]
Super, jetzt hat es auch bei MK geklappt, als sie es selber ändern konnte. 

Du Zaueberer!!! :)
