### ISSUE TITLE
"Corinne," Story ohne Bild

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#129]
- die Story von "Corinne," wurde erstellt, fehlt aber im Dashboard Zauberer Tab und hat kein Bild erstellt (siehe Screenshot der Kundin)
- habe die Vermutung, es lag am Komma hinterm Namen
- ist schon korrigiert, Credit gutgeschrieben für sie und habe sie gebeten, es nochmal zu probieren (steht noch aus)
- wenn es am Komma liegt: können wir zB Sonderzeichen ausschließen beim
Namen? Natürlich keine Bindestriche oder Accents wie é etc. 
- oder anders das Namensfeld schützen, so dass wir solche Probleme vermeiden können? 

![image](https://github.com/livingmydesign/hdstories/assets/159889907/5613f96f-f6a9-4125-885d-0276ad813462)

**Comment by jansthh** [comment]
Info: Nach der Namenskorrektur konnte sie eine neue, fehlerfreie Story generieren

**Comment by livingmydesign** [comment]
Kann sein, dass es hier kurzzeitig einen Ausfall seitens OpenAI gab.
sollte bei einer neuen Story behoben sein.

werde das bei Gelegenheit nochmal gegenchecken.
@jansthh
