### ISSUE TITLE
Intro Seite + Dash fkt. aktuell nicht korrekt

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#130]
- auf hdstories.app bleibt es aktuell beim Ladevorgang (siehe Screenshot)
- Story Erstellung  fkt. aber noch (auch library und inbox etc
- im Dashboard erscheinen aktuell keine Statistiken

![Bildschirmfoto 2024-03-26 um 14 36 47](https://github.com/livingmydesign/hdstories/assets/159889907/343bfe54-16bb-4940-a2bb-b5cf72182170)
![Bildschirmfoto 2024-03-26 um 14 37 06](https://github.com/livingmydesign/hdstories/assets/159889907/a53edce5-52a8-49dc-b9ad-3a8080b08046)

**Comment by livingmydesign** [comment]
@jansthh war wie vermutet eine kleine aber entscheidende sache:
hatte das income-attribute auf "integer" (nur volle zahlen) weil ich dachte, wir nehmen nur ganze zahlen ein. offenbar gabs bei stripe aber auch leichte nachkomma-abweichungen. 

das hat dem integer dann nicht gefallen irgendwann. habs jetzt auf "double" / nachkomma umgestellt auch für das income-attribut.
