### ISSUE TITLE
Story Erstellung stockt bei 2 Usern

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#132]
- Bei diesen beiden (Christin und Isabel) hängt deren Story seit gestern Nacht bei 70%
-  du anderen fkt es weiterhin

![image](https://github.com/livingmydesign/hdstories/assets/159889907/9a712468-db59-4cf9-bc7b-bbf872a6917a)

![image](https://github.com/livingmydesign/hdstories/assets/159889907/0bced3e4-2d5f-4b07-a0de-01a2cceca307)

**Comment by livingmydesign** [comment]
@jansthh sind erstmal zurückgesetzt.
credits wurden keine abgebucht.

für mich als Notiz zum späteren Check:
![Screenshot 2024-03-28 at 08 13 09](https://github.com/livingmydesign/hdstories/assets/93006467/eab0a4e7-6235-40c8-a347-5fb6d3ac95a4)
