### ISSUE TITLE
Tara (Donor) fehlt Story Einladung

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#133]
- Tara (tarafernandezortega@hotmail.com) hat am 26.3. auf Ko-Fi gespendet, aber noch keine Mail erhalten (sie hat in 3 Maileingängen auch Spam Ordner abgesucht)
- sie ist in der Firebase Datenbank, ihre Mail war auch unter den Ko-Fi Spendern, im Dashboard kann ich sie aber auch nicht finden
- magst du das bitte mal prüfen und ihr eine neue Mail schicken?

**Comment by livingmydesign** [comment]
![Screenshot 2024-03-28 at 19 35 45](https://github.com/livingmydesign/hdstories/assets/93006467/f43a2b2d-7a1f-415b-bcc3-79ea0c1117a0)

**Comment by livingmydesign** [comment]
![Screenshot 2024-03-28 at 19 46 11](https://github.com/livingmydesign/hdstories/assets/93006467/6eac2ca9-c2d7-4052-b525-126b0914fd08)

**Comment by livingmydesign** [comment]
Versand von email an tarafernandezortega@hotmail.com werden offenbar von hotmail geblockt.

sie kann uns gerne eine alternative email geben. @jansthh

**Comment by livingmydesign** [comment]
mglw. wurden wir irgendwo (versehentlich) als spam markiert. beobachten.

![Screenshot 2024-03-28 at 19 48 52](https://github.com/livingmydesign/hdstories/assets/93006467/113d7de8-5d8b-4f3a-8d48-9831f3e1045b)

![Screenshot 2024-03-28 at 19 50 28](https://github.com/livingmydesign/hdstories/assets/93006467/86bb2184-4454-4b91-8bfe-83d119ab9838)

**Comment by jansthh** [comment]
tarafernandezortega@gmail.com

**Comment by livingmydesign** [comment]
@jansthh wurde nun nochmals verschickt und sollte auch angekommen sein.
