### ISSUE TITLE
Zb Influencer gratis einladen mit 2 Sterntalern inkl

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#136]
Wenn ich zB Influencer die App ohne Spende ausprobieren lassen will: was wäre hier der einfachste Weg für den sofortigen Zugang? 

Am besten ein Link, den ich ihnen einfach schicken kann?

**Comment by livingmydesign** [comment]
@jansthh guter Punkt. wäre wohl ein Feature für das Dashboard.

Vorschlag, du gestaltest ein entsprechendes Email-Template das die dann kriegen mit dem korrekten Link und ich baue dir das wo mit Email- & Vorname Eingabe-feld ein. 
![Screenshot 2024-03-30 at 13 12 25](https://github.com/livingmydesign/hdstories/assets/93006467/625efe15-7b3f-47a5-9629-866344193b38)

**Comment by livingmydesign** [comment]
![Screenshot 2024-04-01 at 14 39 06](https://github.com/livingmydesign/hdstories/assets/93006467/76ee0176-d1c8-4f0c-a4b8-ca89ef6a7a23)

das ist aktuell das, was ersetzt wird im template

**Comment by livingmydesign** [comment]
![Screenshot 2024-04-01 at 15 12 51](https://github.com/livingmydesign/hdstories/assets/93006467/e6a289dc-27cb-4619-9728-66f83c3897f5)

Sieht dann in der Email aktuell so aus.
@jansthh

**Comment by livingmydesign** [comment]
Das Template kannst du gerne noch weiter anpassen. Die Logik funktioniert, der Account wird mit den gegebenen Credits angelegt und die Einladungsemail wird verschickt.

closed.

**Comment by jansthh** [comment]
- Ich wollte gerade meine 1. Influencer Einladung verschicken 
- leider wird das Textfeld verdeckt in mobile, wenn ich die Nachricht eingeben will
- kann zB zumindest das App Menü ausgeblendet werden, wenn man eine Eingabe macht? 
- und/oder die oberen Menüpunkte nach oben geschoben werden, um das Textfeld freier nutzen zu können? 

![image](https://github.com/livingmydesign/hdstories/assets/159889907/78cdbf14-5905-4e8a-a274-2063df1ee512)

**Comment by jansthh** [comment]
@livingmydesign 

Habe eine Test-Einladung an Bea von info@tarot-academy.de verschickt. Sie sagt, es würde nicht klappen. Siehe Screenshot 🙏🏻

![image](https://github.com/livingmydesign/hdstories/assets/159889907/95fa09d8-71a7-4875-871b-a452f59890ff)

**Comment by livingmydesign** [comment]
@jansthh Ich vermute, dass sie die 8 Sekunden nicht abgewartet hat.. Hab den Link eben getestet mit Icognito Browser und es ladet dann auch:

https://hdstories.app/validate/b62044f458f0dd43ebd8fe9603694bb0/signin
