### ISSUE TITLE
Dashboard Ladeprobleme

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#137]
- das Dashboard lädt sich immer öfter neu und die Seite "stürzt ab" / lässt sich nicht mehr darstellen 

- hängt aus meiner Erfahrung (mit Websites) mit zu vielen Skripten und Elementen zusammen, die gleichzeitig laden (wird schlimmer, je mehr Stories erstellt werden)

- könnte man zB weniger gleichzeitig laden und denn einen MEHR LADEN Button einbauen?

![image](https://github.com/livingmydesign/hdstories/assets/159889907/8552ee0a-402e-4365-ba5a-ed58fe1f4ed2)

**Comment by livingmydesign** [comment]
Jan, ich hab doch gesagt, dass hier heute Baustelle ist :D
@jansthh 

ticket geschlossen.

**Comment by jansthh** [comment]
Das war mir bewusst. 🤓Zu meiner Verteidigung: das ist ein Vorkommen aus den letzten Tagen. Nicht erst seit heute 😌🙏🏻
