### ISSUE TITLE
Dopplungen Donors Datenbank

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#139]
- immer mal wieder bekomme ich durchs Dashboard zufällig mit, dass Sombody oder ein fehlerhafter Name erscheint
- ich bin jetzt mal in der Datenbank alle Donor Mails durchgegangen und habe alle Namen proaktiv korrigiert
- dabei ist bestätigt worden, was mir schon im Dashbaord aufgefallen ist
- es gibt einige Mail-Dopplungen in der Datenbank
- am besten bereinigen wir das schon zu Beginn, bevor es zu viele werden
- kannst du irgendwie abgleichen, welcher Eintrag schon aktiv ist und welcher nicht?
- vielleicht habe ich in der Vergangenheit bei der Namensanpassung nur den ersten von 2 Einträgen angepasst und deswegen hatte sich nichts geändert beim User

**Comment by livingmydesign** [comment]
@jansthh wir sprechen hier von Personen, die mehr als 1mal gespendet haben, richtig?

**Comment by jansthh** [comment]
Das weiß ich leider nicht - müsste ich fairerweise gegenprüfen.

Aber selbst dann, wäre doch eine Bereinigung in der App sinnvoll, oder?

**Comment by livingmydesign** [comment]
<img width="1327" alt="Screenshot 2024-03-30 at 08 21 @jansthh 1" src="https://github.com/livingmydesign/hdstories/assets/93006467/ddcc3454-ea2e-41e7-9d31-9564bacc301e">
@jansthh Absolut sinnvoll. und leider auch etwas aufwendig..

diese paar Doppel-Spender mit mehr als einem Account pro Email bekommen heute ein Email mit ihrem neuen Login-Magic Link.

Die Credits der beiden Accounts werden zusammengerechnet, die Stories zusammengeführt.

**Comment by livingmydesign** [comment]
![Screenshot 2024-03-30 at 08 30 19](https://github.com/livingmydesign/hdstories/assets/93006467/9e165d53-58d0-4341-8ec4-efbe52207a3a)

**Comment by livingmydesign** [comment]
geflickt und gesäubert. *phu*

@jansthh 

ja solche lecks kann dieses schiff echt nicht brauchen, wenn es auf Hohe See ausläuft später.
Da verstärke ich lieber nochmals den Rumpf.
