### ISSUE TITLE
Somebody Name bleibt trotz Änderung in DB

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#140]
Bei folgender Userin ändert sich der Name nicht, obwohl ich ihn in der DB geändert habe

![image](https://github.com/livingmydesign/hdstories/assets/159889907/d6423efc-ec80-4d90-a765-d6a0dff81c77)

**Comment by livingmydesign** [comment]
@jansthh dafür hab ich doch das Menü gebaut.

**Comment by jansthh** [comment]
Ich habe ihr auch ne Mail geschrieben. Aber dass der Name sich nicht zumindest im Dash ändert, wenn ich ihn in der DB ändere: das Problem kannte ich noch nicht 🙏🏻

**Comment by livingmydesign** [comment]
Cache. ¯\_(ツ)_/¯

**Comment by livingmydesign** [comment]
Wenn es in der Datenbank korrigiert ist, sollte in der Regel helfen, den Cache der Seite komplett zu leeren. (am Handy , besonders bei IPhones manchmal nicht eindeutig)
Dann nochmal den Email-Link klicken. 

Ticket wird geschlossen. @jansthh
