### ISSUE TITLE
Laura falsche Geb Daten

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#142]
- Laura Pfandenhauer hat versehentlich die Geb ihres Manns als Stammdaten ("Für mich") eingegeben 
- ihre korrekten Daten: 05.12.1990, 02:15 Uhr, Bad Homburg

- magst du das bitte ändern? Oder kann ich das auch ändern? (Bin gerade unterwegs mit Ava)

- und sollten wir den Usern die Möglichkeit bitten, ihr Geb. Daten bei Fehlern zu korrigieren? Würde uns solche Arbeit abnehmen zukünftig 🙏🏻

![image](https://github.com/livingmydesign/hdstories/assets/159889907/aac128fe-f7df-4782-bd25-ec7b341bd595)

**Comment by livingmydesign** [comment]
@jansthh keine schnelle lösung gerade dazu von meiner seite möglich weil sehr verstrickt.

quick fix: 
a) in gedanken so damit umgehen, dass es der account des mannes ist und entsprechend den vornamen via inbox anpassen und sich selbst mit "für jemand anderen" stories erstellen.
b) nochmal 22€ spenden mit einer anderen emailadresse, dem richtigen vornamen und den richtigen geburtsdaten 

alles andere kommt dann mit dem public release würde ich sagen.
