### ISSUE TITLE
Stephanie Vostinar Donor no Email

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#147]
- Die Spenderin Stephanie Vostinar (gestern Abend) hat keine Mail bekommen und ich finde sie auch nicht in der Firebase unter Donor
- ihre Mail: Humandesign_mondseele@web.de
- laut Ko-Fi hat sie 44,- Euro gespendet, auch mit der o.g. Email
- ich kann sie im Dashboard nicht sehen, in Sendgrid auch nicht, da bin ich mir aber auch nicht sicher, ob ich korrekt gesucht habe (offen für Tipps)
- wie ist hierfür eigentlich die Best Practice? Wenn ein Spender die Mail nicht bekommt bzw. ich sie nochmal schicken wollen würde, ohne dich nerven zu müssen? 

![Bildschirmfoto 2024-04-01 um 11 18 06](https://github.com/livingmydesign/hdstories/assets/159889907/8d545310-afb6-41ac-8944-f465b6527f43)

**Comment by livingmydesign** [comment]
gelöst.
