### ISSUE TITLE
User nicht sicher bei Bday-Daten

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#148]
- Userin Stephanie ist sich nicht sicher bei ihren B-Daten
- bala.kitchen@web.de
- ich weiß, dass wir es gerade nicht ändern können, aber vielleicht sind sie ja korrekt
- sie ist um 5:42 Uhr geboren und denkt, sie hat den Nachmittag angegeben… ;) 
- konnte leider nichts finden in der Datenbank :/

![Bildschirmfoto 2024-04-01 um 12 20 43](https://github.com/livingmydesign/hdstories/assets/159889907/06799ebd-8d1c-4c70-b90f-e1053bae5ab0)

**Comment by livingmydesign** [comment]
<img width="498" alt="Screenshot 2024-04-01 at 13 40 39" src="https://github.com/livingmydesign/hdstories/assets/93006467/a57aab5d-cc11-4f0a-9277-9206eb59750c">

Hat sie richtig angegeben. @jansthh 

geschlossen.
