### ISSUE TITLE
Dashboard Ladefehler

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#151]
- Ich bekomme immer mehr Ladefehler im Dashboard
- er lädt sich ständig von selbst neu - siehe Video
- könnte man vielleicht alle unnötigen Animationen (Fades etc) und Skripte entfernen? Oder vielleicht doch ein paar Dinge auf eine extra Seite schieben?
- normalerweise stürzen Browser immer nur ab, wenn sie zu viele Befehle auf einmal laden müssen
- das Dash scheint immer alles auf einmal zu laden

Für mich ist das Dash zu wichtig. Es ist mit deine beste Idee und Umsetzung. Deswegen wäre es klasse, wenn es irgendwie stabiler laden könnte.🙏🏻

https://github.com/livingmydesign/hdstories/assets/159889907/72a3bbd0-e2c8-4806-b6e0-f1a410420bd1

**Comment by livingmydesign** [comment]
Na sowas. das hatte ich ja noch nie erlebt bei mir. 
Ok.

Wir wäre es damit: Du schreibst mir, welche konkreten Informationen für dich am relevantesten wären für ein Dashboard und ich werde das beim nächsten Mal berücksichtigen wenn ich mich diesem Nebenprojekt widme.  :)

**Ansonsten ja:**
1. Alles und jeder kann & darf warten. 
2. Wenn es mobil ein problem gibt, sollte es am Desktop zumindest halbwegs stabil sein.
3. Wenn du etwas nicht ohne Mühe sofort lösen kannst, schieb es mir rüber und gehe zurück zu 1. :)

@jansthh

**Comment by jansthh** [comment]
Scheint vor allem ein Safari Problem zu sein. Ich rufe das Dash sonst erstmal in nem anderen mobilen Browser auf 🙏🏻
