### ISSUE TITLE
Bonus Story Navigation

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#36]
1) Bonus Story Seite

- ich wähle eine Bonus Story aus
- der Bonus-Screen mit 2 Buttons (neue Story + alte Story) erscheint
- alte Story sollte lieber "letzte Story" heißen
  

![Bildschirmfoto 2024-02-16 um 19 02 59](https://github.com/livingmydesign/hdstories/assets/159889907/e9aedacf-dfa6-47e9-ab76-30c711678e38)

2) Neue Bonus Story Seite

- ich haben neue Story ausgewählt
- Screen mit für mich + für jemanden + zurück erscheinen
- laut Beschreibung wäre "für mich" eine Story mit MEINEN Geb.-Daten
- hier werden aber die ZULETZT (also auch ggf. für jmd. anderen) verwendet
- der Button + die Beschreibung sollten also auf die zuletzt verwendeten Geb.-Daten hinweisen
- ODER der obere Button verwendet wirklich IMMER die zuerst mit dieser Mail verwendeten Geb.-Daten 
- Button Text dann statt "für mich" -> "letzte Daten"
- Button Text stat "für jemanden" -> "ganz neu"

![Bildschirmfoto 2024-02-16 um 19 06 01](https://github.com/livingmydesign/hdstories/assets/159889907/cdab2103-3119-43e8-8402-9bc9808829a9)

**Comment by livingmydesign** [comment]
@jansthh 

> laut Beschreibung wäre "für mich" eine Story mit MEINEN Geb.-Daten

=> tatsächlich werden hier jene Geburtsdaten verwendet, die bei der ersten Account-Erstellung eingetragen wurden. 
(Annahme, dass man beim ersten Mal tatsächlich seine eigenen Geburtsdaten nach Name & Email-Adresse eingibt)

tbd

**Comment by livingmydesign** [comment]
Ist geklärt. wird somit geschlossen.
