### ISSUE TITLE
Storystile fehlerhaft

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#37]
1) Auswahl Storystil

- bei der Auswahl der Stile erscheint jetzt Alice als erstes
- bei folgender Story habe ich auch Alice ausgewählt, er hat aber Harry Potter verwendet: https://hdstories.app/share/ZR1unH
- falsche Verlinkung? bitte prüfen

2) Beschriftung Storystil

- ich denke, der ausgewählte Storystil sollte im Ergebnis auftauchen (tbd)

**Comment by livingmydesign** [comment]
Default-Story-Stil wurde jetzt in der App angepasst. Gerne nochmal testen.

Beschriftung Storystil im Ergebnis: gerne, wenn dafür ein Design entworfen wird. 

@jansthh
