### ISSUE TITLE
Copecart Checkout

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#41]
1) der Link zum copecart Produkt – bitte gern den Text + Info gegenlesen:

https://copecart.com/products/913f209c/checkout

2) Welche Domain sollte die Dankesseite/Weiterleitungsseite bei Copecart haben?

zB https://hdstories.app/order

![IMAGE 2024-02-17 14:23:45](https://github.com/livingmydesign/hdstories/assets/159889907/dba3912d-1dfc-460d-97df-fb73c073cba1)

**Comment by livingmydesign** [comment]
cool, das mit der email funktioniert auch bei copecart:

https://copecart.com/products/913f209c/checkout?email=jansthh@gmail.com

**Comment by livingmydesign** [comment]
Ist jetzt verlinkt und von meiner Seite funktional sowohl auf der /share als auch auf der /story seite.

als Weiterleitung verwende bitte aktuell https://hdstories.app/inbox -> dort können dann stories eingelöst werden.

**Comment by livingmydesign** [comment]
gestern erfolgreich getestet.
