### ISSUE TITLE
Musik Länge

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#43]
- die Hintergrundmusik hört nicht mit der Story auf
- sie läuft einfach weiter bis der Musiktrack endet

Falls sich die Musik nicht dynamisch stoppen (und ausfaden) lässt mit dem Story-Ende, sollten wir sie erstmal entfernen.

**Comment by livingmydesign** [comment]
Ok, ich hab das für mich eigentlich als ein schönes Feature gesehen wie so ein Film-Abspann :)

aber ja. wir können sie auch komplett wieder entfernen.
ein gleichzeitiges Stop mit dem Sprechtext ist aktuell technisch nicht möglich.

bitte dazu kurz noch Bescheid geben.

**Comment by livingmydesign** [comment]
as discussed.
