### ISSUE TITLE
Story Mehrfachkäufe Copecart

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#45]
Könnte ein Kunde schon mehrere Coins kaufen, wenn ich bei Copecart Mehrfachkäufe anbiete? 

Oder lieber einzelne Pakete anbieten? zB 10 Stories Paket für 55,- Euro und dafür dann ein neues Produkt?

**Comment by livingmydesign** [comment]
@jansthh im Prinzip würde es gehen, wenn Leute 10 Stück von einer Story kaufen und dann 10 Story-Credits aufgebucht werden. Das hab ich jetzt mal so für das Produkt "HD Story" vorgesehen und darf dann auch noch getestet werden.

Pakete müssten dann ein eigenes neues Produkt sein, das einen eigenen bestimmten Namen bekommt und andere Credit-Aufbuchungs-Regeln im Backend auslöst.
