### ISSUE TITLE
Story Seite

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#47]
1) Statt Button "Gemeinsam dieses…" Button "Neue Story erwerben" (wie auf der Share Seite)

2) Share Button fkt. nicht auf dem iPhone

Nach der Erstellung einer Story auf dem iPhone kommt weder ein Popup noch wird etwas ins Clipboard kopiert nach dem Klick auf den Share Button (auf der Seite https://hdstories.app/story)

**Comment by livingmydesign** [comment]
Done.
