### ISSUE TITLE
Neuer Menu Link

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#49]
Im Footer erscheint nun die Kombi

Ⓒ HD✨Stories   |   Menu

Bitte den Punkt "Menu" mit neuer Seite verlinken (Fragen Impressum (Impressum Text siehe anderes Issue) Datenschutz)

Beispiel Fragen:

1) Was passiert mit meiner Story, wenn ich den Browser-Tab geschlossen habe?

Nach der Erstellung wird dir deine Story direkt angezeigt und gleichzeitig an deine angegebene E-Mail-Adresse geschickt.

2) Wie kann ich euch bei Problemen und weiteren Fragen erreichen?

Schreibe uns gern eine E-Mail an support@hdstories.app und wir antworten dir baldmöglichst.

3) Wie kann ich meine Story bei Instagram teilen?

Nutze dazu einfach die Bildschirmaufnahme-Funktion deines Handys. Anleitungen: [iPhone](https://support.apple.com/de-de/guide/iphone/iph52f6e1987/ios) und [Android](https://support.google.com/android/answer/9075928?hl=de#:~:text=Smartphone%2DBildschirm%20aufnehmen,um%20die%20Einstellung%20zu%20sehen.&text=und%20ziehen%20Sie%20%E2%80%9EBildschirmaufzeichnung%E2%80%9C%20in%20die%20Schnelleinstellungen.).

4) Was für Pläne habt ihr mit der Stories App?

Sehr große! :) Wir werden Stück für Stück die Features erweitern, zB um einen übersichtlichen Store, mehr Stile, spezielle Stories für Kinder eine Mediathek für alle deine erstellten Stories uvw. – sei gespannt.

![Bildschirmfoto 2024-02-18 um 00 13 35](https://github.com/livingmydesign/hdstories/assets/159889907/6d7638ba-16e6-434a-99a8-0907b6ff32db)

**Comment by livingmydesign** [comment]
Hier mit einem Zurück-Button und Hintergrundbild(Platzhalter) als Banner-Variante zum Reinspüren:
<img width="313" alt="Screenshot 2024-02-20 at 06 13 06" src="https://github.com/livingmydesign/hdstories/assets/93006467/0b6702c3-aba3-4e66-94ac-635958368198">

verlinkt hier:
https://hdstories.app/menu

- [x] Datenschutzbedingungen werden dann noch benötigt.

- [x] Nutzungsbedingungen sind im Beta Release noch nicht nötig, aber sollten spätestens im Public Release dabei sein.
@jansthh

**Comment by jansthh** [comment]
Finde das super und ne schöne Idee mit dem Banner + zurück Icon. Ich hätte nur gern lieber das bereits geschickte SVG Back Icon mit dem dezenteren Pfeil aber inkl. eingefärbtem Hintergrund Kreis :) 

Für Datenschutz brauche ich dann noch nen Moment

**Comment by livingmydesign** [comment]
so? @jansthh 

<img width="308" alt="Screenshot 2024-02-21 at 05 41 47" src="https://github.com/livingmydesign/hdstories/assets/93006467/96500989-7e65-4744-b671-22b352fb2449">

**Comment by jansthh** [comment]
- gern die version mit schwarzem Hintergrund
- insgesamt genauso groß wie dein Pfeil davor (also bestimmt 50% kleiner) -> siehe Bsp im Anhang
- und das HD Stories Logo bitte entweder kleiner oder unten mit mehr Padding und zentriert im Banner 🙏🏻

![image](https://github.com/livingmydesign/hdstories/assets/159889907/62e571e7-aa35-4ba5-94ab-07d90dd8d590)

**Comment by jansthh** [comment]
Zur Datenschutzerklärung:

- ich habe das Gefühl, dass du es viel besser beurteilen kannst aus der Technik-Sicht und als Beauftragter. Ich habe einige Fragezeichen auf der Stirn. Aber dieses Tool ist zB echt simpel, wenn man weiß, was man klicken muss:

https://datenschutz-generator.de/

Zu Copecart (auch im Rahmen vom Datenchutz): Wir müssen unter dem Kauf-Button einen Passus einbauen, weil copecart ja als Verkäufer auftritt. Sonst werden sie das Produkt nicht freigeben:

"Sicherer Kauf über unseren Partner CopeCart"

**Comment by livingmydesign** [comment]
Ich schließe dieses Ticket und mach uns ein eigenes auf für Datenschutz.

**Comment by livingmydesign** [comment]
+ ich hab das Menü nochmal reduziert, finde es passt für diesen Bereich so besser. 
ist klarer

**Comment by jansthh** [comment]
Hier ist noch ein Darstellungsfehler beim aktiven Menüpunkt Datenschutz @livingmydesign 

![image](https://github.com/livingmydesign/hdstories/assets/159889907/65e9e2b3-9d8e-4426-8672-0e88cb9c6adc)

**Comment by livingmydesign** [comment]
sollte nun behoben sein @jansthh
