### ISSUE TITLE
Audio-Text nach der Story

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#50]
1) Gratis Stories

Wir sollten den Text am Ende der gratis Stories noch verändern. Ich bin mir noch nicht sicher, wie. Aber die Aufforderung sollte dahin gehen, dass sie eine weitere kaufen, um uns zu unterstützen.

2) Gekaufte Stories

Bei gekauften Stories der Text ganz wegfallen.

**Comment by livingmydesign** [comment]
1.) Gratis Stories:
du könntest vl. irgendwann auch weitere gratis stories verlosen unter allen, die ihre Story und die neue HDStories Insta-Seite in ihrer Insta-Story tagen. -> mehr reichweite, mehr zulauf, etc.

zum Nach-Text: vielleicht relativ neutral (oder in der 3ten Perspektive) halten, damit er auch passt, wenn die Story an andere (Freunde Familie,..) geteilt wird. also Werbung fürs Projekt, die Idee dahinter und eine Einladung. (kam mir dazu grad)

2.) Gekaufte Stories:
Hab das jetzt so eingestellt, dass Credit-Stories keinen Nachtext mehr haben. Bitte Testen und bestätigen.
@jansthh

**Comment by livingmydesign** [comment]
konnte das eben bestätigen.

@jansthh Bitte noch den neuen Sprechtext nachliefern.

**Comment by jansthh** [comment]
Magst du mir den aktuellen Text bitte nochmal schicken? Finde den nicht mehr und dann muss ich ihn nicht extra abtippen 🙏🏻

**Comment by livingmydesign** [comment]
**Gerne @jansthh :**
Lieber Entdecker.<break time=\"1.0s\" />Hattest du auch das tiefe Gefühl, als käme diese Geschichte direkt aus den Sternen?<break time=\"1.5s\" />Jede dieser Stories ist kunstvoll verwoben aus den Fäden eines Human Design Charts. Und jeder Euro hilft, zukünftig mehr von dieser Kunst erleben zu können. <break time=\"1.0s\" />Bitte teile dein Feedback und spende deinen Betrag, so dass wir diese einzigartige App gemeinsam verwirklichen können.<break time=\"1.0s\" />In liebevoller Dankbarkeit. <break time=\"0.5s\" />Dein Jan.

**Comment by jansthh** [comment]
Danke dir.

Was meinst du?

Lieber Entdecker.<break time="1.0s" />Hattest du auch das Gefühl, als käme diese aus den Fäden eines Human Design Charts verwobene Geschichte direkt aus den Sternen?<break time="1.5s" />Jede Story erzählt liebevoll über deine Einzigartigkeit und möchte dich in der Tiefe deines Seins berühren. <break time="1.0s" />Teile sie mit deinen Liebsten und erstelle jederzeit neue, einzigartige Geschichten in unserer Human Design Stories App.<break time="1.0s" />In liebevoller Dankbarkeit. <break time="0.5s" />Dein Jan.

**Comment by livingmydesign** [comment]
gekauft.

**Comment by livingmydesign** [comment]
vielleicht noch ein wenig anpassen hin Hinblick dessen, dass diese "Trial"-Story nur ein kleiner Vorgeschmack ist auf die Stories, die man erwerben kann? @jansthh

**Comment by livingmydesign** [comment]
@jansthh 

Das tolle hier ist ja, dass du diesmal diesen Schluss-Text auch selbst aufzeichnen könntest, weil es ein fertiges mp3 sein wird, das drangehängt wird. würde die Wirkung u.U. vl. sogar nochmal erhöhen.

**Comment by jansthh** [comment]
Mag das jetzt erstmal abschließen und zukünftig einfach stetig optimieren. 

"Lieber Entdecker. Hattest du auch das Gefühl, als käme diese aus den Fäden eines Human Design Charts verwobene Geschichte direkt aus den Sternen? Diese kostenlose Story ist nur ein kleiner Vorgeschmack auf unsere besseren, längeren und vielfältigeren Stories, die du für einen kleinen Betrag kaufen kannst – natürlich auch ohne diesen Zusatz am Ende. Jede Story erzählt liebevoll über deine Einzigartigkeit und möchte dich in der Tiefe deines Seins berühren. Teile sie mit deinen Liebsten und zaubere jederzeit neue, einzigartige Geschichten in unserer Human Design Stories App. In liebevoller Dankbarkeit. Dein Jan."

**Comment by livingmydesign** [comment]
Done, ist ausgetauscht. @jansthh
