### ISSUE TITLE
Namen nochmal ändern

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#51]
- wenn ich den Namen nochmal ändern will, kann ich nicht auf auf zurück gehen
- Das klappt natürlich nicht und ich musste einen neuen Magic Link anfordern.
- Es kann aber gut sein, dass die Leute sich verschreiben oder dann doch für jemand anderen eine Story erstellen lassen wollen.

-> Können wir irgendwie einbauen, dass wir zurück zum Namen kommen während des Prozesses?

**Comment by livingmydesign** [comment]
wird layout-mäßig eine Herausforderung, aber vielleicht fällt mir dazu noch was ein.

**Comment by jansthh** [comment]
Kann man den Namen vielleicht irgendwie nochmal clearen? Oder einfach nochmal beim Namen beginnen, wenn man sich vertippt hat oder doch eine Story für den Sohn erstellen will? 

Mir ist das jetzt schon ein paar Mal passiert und dann muss ich die Story einmal ganz erstellen

Das wird Käufer sicher verärgern. Was meinst du?

**Comment by livingmydesign** [comment]
done
