### ISSUE TITLE
Sendgrip Upgrade zum Launch

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#52]
- Account Upgrade zum Launch

**Comment by livingmydesign** [comment]
Yes, das wäre dann wohl dran 👍

**Comment by jansthh** [comment]
Wollte das gerade machen, finde diese spezielle Upgrade aber nicht mehr. Kannst du mir helfen @livingmydesign ? :)

**Comment by livingmydesign** [comment]
aber sischa:
https://app.sendgrid.com/account/products
![Screenshot 2024-02-22 at 04 52 28](https://github.com/livingmydesign/hdstories/assets/93006467/940d6efc-815a-4e6a-adc8-57846645c12a)

**Comment by jansthh** [comment]
Danke & Done
