### ISSUE TITLE
Sendgrid Templates Texte+Feeling

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#53]
alle templates prüfen und texte optimieren + bild dankbarkeit für doners

**Comment by jansthh** [comment]
Done

**Comment by livingmydesign** [comment]
Sehr gut. Passt.

Zum Schließen von Issues kannst du auch gerne selbst auf den "Close with comment" Button unten klicken wenn du das ab-haken möchtest :)

**Comment by livingmydesign** [comment]
Ich schließe das mal für dich jetzt :)
