### ISSUE TITLE
Story Link in E-Mail

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#54]
Muss der Link unter "Kopiere deinen Story Link zum Teilen:" so "nicht schön" aussehen oder darf der auch hinter einen Text bzw. Button? :)

![Bildschirmfoto 2024-02-18 um 22 34 33](https://github.com/livingmydesign/hdstories/assets/159889907/ed7412b1-4f5d-44b0-b767-30e65f381663)

**Comment by livingmydesign** [comment]
Hinter einem Button ist er ja schon hier. 
das "https:/" könnte wegfallen noch. 

War gedacht für jene, die das "Kopieren" lieber mit dem Mauszeiger direkt machen als einen link aus der Adress-leiste rauszukopieren. 

Wie du meinst - sag einfach Bescheid. @jansthh

**Comment by jansthh** [comment]
Okay, dann bitte ersatzlos streichen inkl. Überschrift (Link zum Teilen). Soviel dürfen wir unseren Usern zutrauen. Er kann ja auch den Link aus dem Button kopieren oder dann halt den Browserlink nach Aufruf. Weniger ist mehr und das sieht wirklich unschön aus so mit dem Textlink ;)

**Comment by livingmydesign** [comment]
Done. 
<img width="643" alt="Screenshot 2024-02-21 at 05 45 14" src="https://github.com/livingmydesign/hdstories/assets/93006467/40689b7f-71ca-4ec6-8bc8-4f4c5d34e323">
