### ISSUE TITLE
Bild Prompt Ideen

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#55]
Loading Screens Ideen:

1) "Chart mit Samthandschuhen": https://www.midjourney.com/jobs/fd6435fb-7e52-4b20-870a-7e48e254dd52

2) "Chart inspizieren und polieren": https://www.midjourney.com/jobs/6a88ca69-c46d-4b49-b6dd-d2c1ddef7d79 + https://www.midjourney.com/jobs/3684b5a3-a9cc-4b0b-b2e0-420fcc50aa31

3) "Jan nimmt Audio auf": https://www.midjourney.com/jobs/413cab3b-f376-41ca-81df-090d5b55bec0?index=3

4) "Wunderbare Feier": https://www.midjourney.com/jobs/d8805fbf-d496-4789-af8e-f586f202353a?index=0

5) "Umschlag Versand": https://www.midjourney.com/jobs/daaae1d9-22f5-45c6-b7f4-629c8b3e23b2 + https://www.midjourney.com/jobs/8bafa025-6a71-44a8-bfc1-1f6f5451bced

Weitere Ideen:

https://www.midjourney.com/jobs/a89a9498-71c9-4531-8a82-8c1228605f92?index=3

https://www.midjourney.com/jobs/e73c00db-9834-4b8a-b72e-3ef666ec2a90?index=1

https://www.midjourney.com/jobs/e73c00db-9834-4b8a-b72e-3ef666ec2a90?index=0

https://www.midjourney.com/jobs/1de5a3e9-ffb1-4b8f-8845-258edfc4152e?index=0

https://www.midjourney.com/jobs/9f2432de-c362-4c73-801d-f1d4d1234b18?index=0

https://www.midjourney.com/jobs/2fc45ff3-85a8-43ee-9467-c1c96465a5c3?index=0

https://www.midjourney.com/jobs/999b3b03-7632-4918-a69b-841c7733a9f1?index=0

https://www.midjourney.com/jobs/bc836daf-712a-41b9-9e0d-b76a0ddc07e3?index=0

https://www.midjourney.com/jobs/16a35905-94a7-4cd8-ada0-54ccd0e15129?index=0

https://www.midjourney.com/jobs/bc836daf-712a-41b9-9e0d-b76a0ddc07e3?index=1

https://www.midjourney.com/jobs/a4297890-5030-432b-ba82-56b4d3349ed9?index=0

https://www.midjourney.com/jobs/1f8099a4-bcde-4c38-b15a-5cc2f388291b?index=3

https://www.midjourney.com/jobs/8df87637-fd66-4f2f-925b-76e08897f9c0?index=0

https://www.midjourney.com/jobs/504cb3c8-bc47-4cd2-b06a-79ce3cdfe594?index=0

https://www.midjourney.com/jobs/5abe85d9-14ed-47bd-9d16-bf1fea63fdad?index=0

https://www.midjourney.com/jobs/01695d32-a2e2-47bb-8f49-c43c434f969e?index=0

https://www.midjourney.com/jobs/a11d6cbb-e13a-45e7-80e3-695402352c77?index=1

https://www.midjourney.com/jobs/2551c090-19d9-4442-a15c-6f02915a4b63?index=0

**Comment by livingmydesign** [comment]
done
