### ISSUE TITLE
11labs Pausen

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#56]
habe in nem Review gesehen, dass der Pause-Code deutlich besser funktionieren soll als "…" und sich auch natürlicher anhören soll (2s steht für 2 Sekunden – 1.5 wäre ein anderer Wert):

<break time="2s"/> 

könnte natürlich sein, dass es für gpt komplizierter ist, das anstelle von … einzubauen 🙏🏻

**Comment by livingmydesign** [comment]
Ja, das haben wir bereits so drinnen, dass Absätze etc. mit diesem code für 11labs ersetzt werden. 

oder hast du konkrete Story-Beispiele, wo die Pausen noch länger sein sollten?

**Comment by livingmydesign** [comment]
Sollte aktuell Ok sein da es dazu keine weiteren Kommentare gab.
Ticket wird geschlossen. @jansthh
