### ISSUE TITLE
Bonus Story nicht angezeigt bei meinem Account + 2 Bugs

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#60]
- Habe eben für die Nachbarstochter Paulina eine Story gemacht und da wurde mir nur "Story erwerben" angezeigt.

- am Ende der Story kam ein Versprecher -> vielleicht noch ein fehlerhafter elevenlabs-Befehl?

- Hintergrundmusik fehlte

https://hdstories.app/share/f05EdR

![image](https://github.com/livingmydesign/hdstories/assets/159889907/cd78d3a8-43ee-43bd-83a6-249aae80ee2d)

**Comment by jansthh** [comment]
@livingmydesign Hello. Die o.g. Fehler bestehen immer noch, inklusive dem schrägen Versprecher ganz am Ende bei den Premium Stories ohne Werbung (sicher ein 11labs Pause Befehl, der noch entfernt werden muss ) sowie "Storylink kopieren" Button fkt. in keinem mobilen Browser auf dem iPhone (Safari, chrome, Firefox) 🙏🏻

**Comment by livingmydesign** [comment]
sollte nun behoben sein mit dem Musik- & Elevenlabs Upgrade.
@jansthh 

ticket wird geschlossen.
