### ISSUE TITLE
Offene Todos für Datenschutzhinweis

### ISSUE THREAD

**Issue by livingmydesign** [livingmydesign/hdstories#61]
aktuelle Fassung der Datenschutzerklärung:
https://hdstories/menu -> bitte gerne den Textstil in Flutterflow noch anpassen wo nötig:

================================

Zuletzt aktualisiert am 22. Februar 2024

Hey! Schön, dass du dich für "HDStories" interessierst. Wir, also Jan Stiewe und das Team hinter HDStories, nehmen deinen Datenschutz ernst. In diesem Hinweis erklären wir dir, wie und warum wir deine Infos sammeln, speichern, nutzen und/oder teilen könnten, wenn du unsere Dienste nutzt. Das gilt zum Beispiel, wenn du:

Unsere Webseite besuchst oder eine unserer Apps nutzt, die auf diesen Datenschutzhinweis verlinkt.
Mit uns auf andere Weise in Kontakt trittst, z.B. über Verkauf, Marketing oder Events.
Fragen oder Bedenken? Dieser Hinweis hilft dir, deine Datenschutzrechte und -optionen zu verstehen. Wenn du mit unseren Richtlinien und Praktiken nicht einverstanden bist, nutze unsere Dienste bitte nicht. Bei weiteren Fragen oder Bedenken kannst du uns gerne unter **privacy@hdstories.app** kontaktieren.

**Kurz und Knapp**
Hier findest du die wichtigsten Punkte aus unserem Datenschutzhinweis, aber mehr Details zu jedem Thema findest du, wenn du den Links folgst oder im Inhaltsverzeichnis nach dem gesuchten Abschnitt suchst.

**Welche persönlichen Infos verarbeiten wir?**
Wenn du unsere Dienste besuchst, nutzt oder dich durch sie navigierst, können wir persönliche Informationen verarbeiten, je nachdem, wie du mit HDStories und den Diensten interagierst, welche Entscheidungen du triffst und welche Produkte und Funktionen du nutzt.

**Verarbeiten wir sensible persönliche Informationen?**
Nein, wir verarbeiten keine sensiblen persönlichen Informationen.

**Erhalten wir Informationen von Dritten?**
Nein, wir erhalten keine Informationen von Dritten.

**Wie verarbeiten wir deine Informationen?**
Wir verarbeiten deine Informationen, um unsere Dienste bereitzustellen, zu verbessern und zu verwalten, mit dir zu kommunizieren, für Sicherheit und Betrugsprävention und um gesetzliche Anforderungen zu erfüllen. Wir können deine Informationen auch mit deiner Zustimmung für andere Zwecke verarbeiten.

**In welchen Situationen und mit welchen Arten von Parteien teilen wir persönliche Informationen?**
Wir können Informationen in bestimmten Situationen und mit bestimmten Kategorien von Dritten teilen.

**Wie schützen wir deine Informationen?**
Wir haben organisatorische und technische Prozesse und Verfahren, um deine persönlichen Informationen zu schützen. Allerdings kann keine elektronische Übertragung über das Internet oder Informationsspeichertechnologie als 100% sicher garantiert werden.

**Welche Rechte hast du?**
Abhängig von deinem geografischen Standort hast du möglicherweise bestimmte Rechte bezüglich deiner persönlichen Informationen.

**Wie kannst du deine Rechte ausüben?**
Am einfachsten ist es, deine Rechte auszuüben, indem du unser **Formular für Datenanfragen** ausfüllst oder uns kontaktierst. Wir werden jede Anfrage gemäß den geltenden Datenschutzgesetzen bearbeiten.

**Willst du mehr darüber erfahren, was wir mit den Informationen machen, die wir sammeln?**
Schau dir unseren **vollständigen Datenschutzhinweis** an.

Denk daran, dass du immer die Kontrolle über deine Daten hast und wir hier sind, um jede deiner Fragen zu beantworten. Falls du irgendwelche Bedenken hast, zögere nicht, uns zu erreichen. 

Wir sind für dich da!

==============================

Formular für Datenschutzanfragen:
https://docs.google.com/forms/d/e/1FAIpQLSf7kgYKSVToaXuF47rNx4dVG13XgFByGxHRfCb_fjwbvFkJJQ/viewform?usp=sharing

Dazu ist noch zu erledigen:
- [ ] privacy@hdstories.app anlegen (wenn solche Email gesondert behandelt werden sollen) **=> Jan**

- [ ] Anfrage-Formular auf den Google Account von Jan umziehen -> inkl. Email-Benchrichtigung und Verknüpfung mit Google Sheet for Eingänge **=> Jan**

- [x] Ausführliche Datenschutzerklärung erstellen. Kann auch ein PDF sein, das man öffnen/runterladen kann. **=> Werde ich übernehmen.** : https://docs.google.com/document/d/1cSot-d0k-8R49HkNyAZIGKyVqJ4lZ4wayDKtImut81M/edit?usp=sharing

**Comment by livingmydesign** [comment]
Ok, für den Beta-Release würde erstmal diese Version hinterlegen als "ausführliche Datenschutzerklärung":

https://docs.google.com/document/d/1cSot-d0k-8R49HkNyAZIGKyVqJ4lZ4wayDKtImut81M/edit?usp=sharing

@jansthh 

für den Public Release gebe ich mir dann gerne nochmal mehr Mühe. vielleicht ;)

**Comment by livingmydesign** [comment]
@jansthh bitte von dir noch einzurichten:
1.) [privacy@hdstories.app](mailto:privacy@hdstories.app) anlegen (wenn solche Email gesondert behandelt werden sollen) => Jan

 2.) Anfrage-Formular auf den Google Account von Jan umziehen: 
 -https://docs.google.com/forms/d/e/1FAIpQLSf7kgYKSVToaXuF47rNx4dVG13XgFByGxHRfCb_fjwbvFkJJQ/viewform?usp=sharing
 => einfach kopieren in deinen Google-Account und danach den Share-Link hier reinstellen, damit ich ihn in die Datenschutzbestimmungen einpflegen kann.

**Comment by jansthh** [comment]
- würde solche Anfragen (die wohl nie geschehen?) zunächst auch an support@hdstories.app gehen lassen 

- Hier das neue Formular: https://forms.gle/gjDyPHDSpbAtPU6u5

**Comment by livingmydesign** [comment]
Done. @jansthh
