### ISSUE TITLE
"Data Issue"

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#62]
Wenn ich aktuell  mit meinem Desktop Browser (Chrome) eine Story erstellen möchte, erscheint folgender Screen:

![Bildschirmfoto 2024-02-27 um 09 42 07](https://github.com/livingmydesign/hdstories/assets/159889907/39824ae2-3060-4f52-ad32-b5517f0bcd6a)

**Comment by jansthh** [comment]
FYI: Kommt aktuell nicht mehr vor, seitdem ich Cookies und Cache gelöscht habe

**Comment by livingmydesign** [comment]
Ok gut. Danke fürs Informieren.
