### ISSUE TITLE
Alle Stories "brechen aktuell ab am Ende

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#63]
Bei den letzten Stories war immer das Ende immer zu abrupt und es fehlte etwas und es kamen Sprachfehler

**Bsp 1:**

https://hdstories.app/share/Jqd2FZ

Text am Ende:

"Bist du bereit?", hauchte eine -> Abbruch

**Bsp 2:**

https://hdstories.app/share/NX9Fba

Text am Ende:

Jen wies sie auf einen verborgenen Pfad hin, der sich hinter einem Vorhang aus schimmerndem Moos öffnete, und beobachtete, wie Erstaunen ihre Gesicht -> Abbruch

**Bsp 3:**

https://hdstories.app/share/Xs4oLl

Text am Ende: 

Du kannst sehen, was andere nicht sehen...", sagte eine ältere Frau zu ihm, die in seinen Augen eine Weisheit zu erkennen glaubte, die weit über das Sichtbare hinausging. Jan nickte lächelnd. " -> wirkt auch nicht wie das Ende

**Bsp 4:**

https://hdstories.app/share/EqWV9G

Text am Ende:

Jan lächelte nur -> Abbruch

**Comment by livingmydesign** [comment]
@jansthh Ich vermute mal, das liegt indirekt am Kürzen der Trial-Stories auf 60-100 Worte. 
Hab den Prompt mal etwas angepasst zum Testen.

**Comment by jansthh** [comment]
Habe es gerade nochmal probiert. Passiert immer noch. Sie Text Excerpt:

https://hdstories.app/share/6fyxnI

**Comment by livingmydesign** [comment]
Ok, hab das Problem gefunden und behoben: Offenbar wurde durch ein Update bei Make ein Token-Limit von 300 Tokens wirksam, dass ich irgendwann eingestellt und vergessen hab. War bisher nicht wirksam wie's scheint.

Sollte jetzt behoben sein - hab das Limit auf 1500 Tokens erhöht, was dann 5000 Zeichen wären und somit auch die Obergrenze von 11Labs 

@jansthh

**Comment by livingmydesign** [comment]
Bitte nochmal testen und bestätigen. Danke

**Comment by jansthh** [comment]
Hat geklappt! Super 🥳

**Comment by livingmydesign** [comment]
somit geschlossen.
