### ISSUE TITLE
Falsche Story abgespielt

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#64]
Eben hat er meine zuletzt erstellte Story angezeigt und abgespielt, obwohl im Browser der korrekte Link angezeigt wurde und ich auch die korrekte zugeschickt bekommen haben

Das ist dir korrekte Story, die eigentlich abgespielt hätte werden müssen:

https://hdstories.app/share/EqWV9G

Diese Story hat er aber angezeigt und abgespielt (nach Browser Refresh hat er die obige abgespielt):

https://hdstories.app/share/Jqd2FZ

**Comment by livingmydesign** [comment]
Bitte erneut testen. @jansthh

**Comment by jansthh** [comment]
die letzten Male ist das nicht mehr vorgekommen. Ich werde das weiter beobachten.

**Comment by livingmydesign** [comment]
vorerst geschlossen.
