### ISSUE TITLE
Ladescreens "library" Headline

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#65]
Ich habe den Ladescreen as good as it gets optimiert, so dass deine schönen neuen Bilder im Hintergrund sichtbarer werden. Nur bei der Headline habe ich es aktuell nur temporär gelöst mit 350px Padding unten (was auf kleineren Screesn natürlich alles zerschießt).

- bitte die Headline "Deine Story wird erstellt" oben wie im Screenshot unter dem Logo neu platzieren

![Bildschirmfoto 2024-02-27 um 16 04 01](https://github.com/livingmydesign/hdstories/assets/159889907/a2504d33-6898-4de5-9879-33d9e74ef710)

**Comment by livingmydesign** [comment]
done. @jansthh
