### ISSUE TITLE
Story / Share Screen mit erwerben Button + Admin Footer Leiste Desktop

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#66]
1) Meistens erscheint trotzt Credits zunächst des Button "Neue Story erwerben" unter einer neuen Story -> nach einem Browser Refresh kommt wieder der Button "Eine neue Story zaubern" 

2) Auf dem Desktop erscheint bei mir aktuell noch eine Admin Leiste im Footer

beides siehe Screenshot

![Bildschirmfoto 2024-02-27 um 15 56 18](https://github.com/livingmydesign/hdstories/assets/159889907/2d4a3f61-d682-4bf5-a79e-3c226b322291)

**Comment by livingmydesign** [comment]
der Admin-Balken sollte nur sichtbar sein, wenn der User als Admin markiert ist.
@jansthh 

das sollte bei deinem User gar nicht mehr der Fall sein.
wurde der Cache am Browser schon länger nicht mehr gelöscht?

**Comment by livingmydesign** [comment]
@jansthh konnte einen solchen fehler nicht mehr sehen bei meinen tests.
wird nur gezeigt, bei admin-usern.
