### ISSUE TITLE
Neue Hintergründe Ladescreens Desktop

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#67]
- Bilder sind noch im quadratischen Format auf dem Desktop statt 7:5 oder 16:9 (soll ich die neuen Bilder erweitern in Photoshop?)
- Bilder wirken zu gering aufgelöst und dadurch verpixelt (hast du sie noch nicht in High Res hochgeladen?)
- zudem werden teils noch alte Screens dargestellt auf dem Desktop
- bitte alle bilder einmal hochskalieren in midjourney und mir schicken -> ich erweitere dann links und rechts und speichere fürs Web

siehe Screenshot

![Bildschirmfoto 2024-02-27 um 16 03 12](https://github.com/livingmydesign/hdstories/assets/159889907/f990a890-d02b-454f-bf40-0563d247b7f4)

**Comment by livingmydesign** [comment]
done: hochgeladen und ausgetauscht. @jansthh
