### ISSUE TITLE
Adjusted Intro Screen

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#68]
- bitte mein Portrait entfernen
- den Story Counter oben unter das Logo setzen
- die Headline auch darunter
- button so weit nach unten setzen, so dass das Gesicht des kleinen Prinzen sichtbar ist
- Text darunter setzen

Finde diesen Screen und unser Key Visual sehr wichtig. 

![Bildschirmfoto 2024-02-27 um 16 22 54](https://github.com/livingmydesign/hdstories/assets/159889907/23ea231c-5fda-491d-a4f4-bc2526006194)

**Comment by livingmydesign** [comment]
done. @jansthh
