### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#69]
Ich hatte nun schon oft den Impuls, aber ich glaube, wir sollten "Name, du lieber Mensch" mal rausnehmen.

Mir ging es immer nur darum, dass der User mit dem Vornamen geschlechtsneutral angesprochen wird. Aber das geschieht ja fast immer direkt zu Beginn der Story. 

Er spricht das auch meistens sehr seltsam aus. Und ohne diese seltsame Begrüßung steht die Story nochmal mehr für sich.

Was meinst du?

**Comment by livingmydesign** [comment]
done. @jansthh 
bitte mal testen.

**Comment by jansthh** [comment]
Viel besser 👌🏻🙏🏻
