### ISSUE TITLE
iPad Touch fkt.

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#70]
Aus irgendeinem Grund reagiert kein Element auf dem iPad auf Gouch Gesten. Weder das lange Drücken auf "Jetzt unterstützen" noch auf "Menu"

So kann ich auf dem iPad nicht testen

**Comment by livingmydesign** [comment]
@jansthh lassen sich die Story-Links mit dem IPad bedienen?

play-stop-bild, etc.

+ share-button?

**Comment by jansthh** [comment]
@livingmydesign Was fkt auf der Shared Story Seite: play/stop, image zoom, text reveal, buy button, animierter Wechsel zwischen Share/buy button, menu button

Was nicht fkt: share button link (wie beim iPhone, sicher ein iOS Ding), und auf der Startseite der App nur der Link zu Kofi (es fkt auch nicht der Menu Button im footer,der auf der Shared Story Seite fkt)

Habe es auch in chrome und Firefox auf dem iPad getestet

**Comment by livingmydesign** [comment]
ok, werde ich prüfen.

**Comment by livingmydesign** [comment]
@jansthh Menü-Button sollte nun funktionieren:

um rein zu kommen via iPad: click auf counter, click auf intro-text, click auf große Überschrift.

bitte Testen & bestätigen.
allenfalls davor den Browser-Cache noch leeren.

**Comment by jansthh** [comment]
Hat geklappt, danke. Cache Themen sind teilweise echt hartnäckig unter iOS… 

Wie gesagt, nur erstellt er nach wie vor meine Stories "für mich" mit den Daten des 1/3 Manifestor Jans :-/

**Comment by livingmydesign** [comment]
Danke. somit geschlossen.
