### ISSUE TITLE
Ladeprobleme

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#71]
bei den letzten Tests heute gibt es teilweise auffällig lange Ladezeiten und Fehlerscreens wie diesen im Anhang, den ich noch nicht gesehen hab vorher

![image](https://github.com/livingmydesign/hdstories/assets/159889907/3bd22bdc-715a-4ebf-a6fc-b960c1ff368a)

**Comment by livingmydesign** [comment]
@jansthh und das war nur für die URL **hdstories.app** ohne zusätzlichem Pfad?

**Comment by jansthh** [comment]
Kann ich leider nicht sagen. Ich meine, es waren Unterseiten. Aber es kam jetzt beim ganzen Testen nicht mehr vor und die Performance ist auch wieder da.

**Comment by livingmydesign** [comment]
ok. dann schließe ich dieses ticket vorerst.
