### ISSUE TITLE
Verschiedene Bilder in 1 Story

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#75]
Zufällig ist mir aufgefallen, dass in einer Story 2 verschiedene Bilder in der Mail und online verwendet wurden:

https://hdstories.app/share/k95oD3

![image](https://github.com/livingmydesign/hdstories/assets/159889907/ba3a3545-df2f-4106-9be9-66ba12e7e70b)

![image](https://github.com/livingmydesign/hdstories/assets/159889907/72dab640-70c3-4110-9adb-cdc0f1a0cd68)

**Comment by jansthh** [comment]
das Bild im Screenshot erscheint nur auf meinem iPhone im Safari Browser. Auf dem Mac, dem iPad und einem anderen Browser auf dem iPhone kommt das aus der Mail. Ist also wohl (nur) ein Cache Problem

**Comment by livingmydesign** [comment]
In diesem Fall war die Email-Gil Variante die korrekte. 

warum er hier ein altes Bild noch angezeigt hat, liegt vmtl. tatsächlich an einem cache-thema.
ich werd sehen, ob ich dazu etwas im code finde.

@jansthh 

bitte weiter beobachten und reporten, falls es nochmal auftritt.

**Comment by jansthh** [comment]
bisher ist es nicht wieder vorgekommen. Nur, dass Gils Story im iPhone Safari Browser hartnäckig das andere Bild anzeigt bei korrekter Story. Aber das ist offensichtlich ein Cache Problem

**Comment by livingmydesign** [comment]
@jansthh ja, wie gesagt, das bild mit dem Bart-Mann ist das korrekte Gil-Bild und wird mir so auch in Chrome & Safari angezeigt: 
![Screenshot 2024-03-06 at 05 13 11](https://github.com/livingmydesign/hdstories/assets/93006467/0b3e6058-2d28-49f1-9c90-88459b350bcd)

https://hdstories.app/mystory/k95oD3

**Comment by livingmydesign** [comment]
interessant für mich wäre an der Stelle ja, herauszufinden, von welcher Story der kein-bart-gil war. 

aber erstmal würde ich es als ein kurzfristiges phänomen betrachten, das möglicherweise durch einen anderen bugfix mittlerweile nicht mehr auftreten kann. @jansthh
