### ISSUE TITLE
Scrollable Story Page

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#76]
- Ich würde dem Bild und damit der Story gern noch mehr Space geben (siehe Bsp) und habe dazu das Verhältnis von 50/50 zu 60/40 geändert (Story Container zu footer container)

- dafür müsste wir zumindest bei der Story Page (aktuell ja "share" -> vielleicht noch umbenennen zu "story"?) die Scroll Funktion aktivieren

-> ist das schnell umsetzbar? 😍 falls nicht, ändern wir es einfach wieder auf 50/50 🙏🏻

![image](https://github.com/livingmydesign/hdstories/assets/159889907/7ffa2dd2-4a32-4720-9285-cdd4f12cbd0c)

**Comment by livingmydesign** [comment]
@jansthh  bitte erneut testen. scrolling ist eingefügt.

hdstories/share -> lädt imho zu viral ein
vs
hdstories/story -> wird repetitive auf mich

**Comment by jansthh** [comment]
@livingmydesign vielleicht dann sowas wie

/mystory

oder

/share ist zwar eindeutig aber auch so unpersönlich

es sollte kurz und prägnant bleiben, aber einen persönlichen Touch haben. die meisten werden das ja nie sehen und bei der App ist es irrelevant.

**Comment by livingmydesign** [comment]
Ok. 

Ich brauche dazu nur deine endgültige Entscheidung weil der Link dann auch für die Emails etc. angepasst werden muss.

also hdstories/mystory ?

kannst ja allenfalls GPT fragen für eine auswahl und dich dann entscheiden.
@jansthh

**Comment by livingmydesign** [comment]
@jansthh done.

Hinweis: dadurch funktionieren natürlich auch alle bisherigen share-links nicht mehr.

**Comment by jansthh** [comment]
Danke 🙏🏻

Ist natürlich nicht schlimm. Aber wäre nicht ein einfacher redirect dafür möglich?

**Comment by livingmydesign** [comment]
ja, aber ich will möglichst nicht zusätzliche Seiten pflegen, die nur dafür da sind, um alte Strukturen aufrecht zu erhalten.

waren ja eh noch keine User von Außen, oder?

**Comment by jansthh** [comment]
Muss es für einen Redirect eine extra Seite geben? Wenn ich bei alten Stories mystory gegen share tausche, fkt. die ja noch alle.

Ein paar Leuten habe ich ja schon Stories geschickt, die jetzt erstmal in die Röhre gucken. Wenn es einfach ist (kenne das bei Linkänderungen bei Websites), wäre es klasse. :))) Wenn es zu kompliziert ist, ist es natürlich okay 🙏🏻
