### ISSUE TITLE
Abo Modell mit Credits

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#77]
- wenn ich in CopeCart für unsere Stories App ein Abo anlege, dass automatisch jeden Monat abbuchen würde

- könnten wir dann per Webhook festlegend dass jeden Monat Credits aufgefüllt würden? (Am besten verfallen sie dann nach 1 Monat oder spätestens 2)

- zB 22,-/Monat bekommt der User 5 Credits

Das wäre so genial! Dann hätten wir sofort regelmäßige Einmahmen und der User müsste sich keine Gedanken machen

**Comment by livingmydesign** [comment]
dazu müsste man prüfen, ob der normale webhook-kaufprozess von copecart durchgeführt wird bei so einem abo-modell.
falls ja, macht es für unser system keinen unterschied. credits werden aufgebucht. -> gerne prüfen (lassen)

Hab dazu jetzt auch mal die Zaubermünzenanzeige (du findest vl. noch einen besseren Naben dafür ;) ) eingebaut in die inbox @jansthh 

einzelne credits mit ablaufdatum: u-uh. -verstehe den Gedanken dazu, aber das wäre ein heavy lift und würde vmtl. auch nicht gut ankommen.. 🤔 => mehr durchdenken vl. noch. "Warum haben meine gekauften Münzen ein Ablaufdatum?" muss schlüssig beantwortet werden können.

**Comment by jansthh** [comment]
- ich habe eine Anfrage an CopeCart dazu gestellt, ob die Webhooks monatlich bei einem Abo Produkt geschickt werden, damit die Credits automatisiert aufgeladen werden könnten in unserer Web App (und nicht nur einmalig zu Beginn, wenn der Kunde das Abo abschließt)

- Super genial mit der Zaubermünzen-Anzeige 😍 Du hast schon so viel Geniales erschaffen!! 

- Namen für Zaubermünzen: Storytaler, Sternentaler, Storycredits, Storymünzen, Zaubercredits (ich soundboarde nochm vielleicht reagiert dein Sakral auf etwas)

- ich dachte halt an sowas wie 11Labs oder Datenvolumen beim Handy  – was die Leute schon gewohnt sind. Auf der anderen Seite könnte man sie natürlich immer weiter auffüllen lassen. Hmm

**Comment by jansthh** [comment]
@livingmydesign  Copecarts Antwort:

"Da bei einem Abo jeden Monat eine Zahlung gibt, werden die Webhooks auch jeden Monat getriggert, sodass die Kunden seine Credits erhalten."

**Comment by livingmydesign** [comment]
@jansthh ich finde die "SternTaler" schön. weils ja auch eine eigene Märchengeschichte dazu gibt und HumanDesign und Sterne etc. finde ich passt gut. Verbindung Himmel und Erde. Sterne und Täler. :D

ich setze es mal ein, bis du was anderes willst.

Gut, mit den CopeCart Zahlungen.

**Comment by jansthh** [comment]
Merci.

Ich schwanke auch noch zwischen Sternentaler und Storytaler (wäre etwas konkreter für den DAU ;) )
