### ISSUE TITLE
Play Icon Delay

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#78]
- Gibt es einen notwendigen Grund, warum du 1000ms Beim Play Icon eingestellt hast? (wenn ich das richtig verstanden habe)

- falls nicht, sollten wir das deutlich reduzieren – fast auf 0 -> aktuell ist eine ganz seltsame Verzögerung damit verbunden und könnte zu Doppelklicken führen

![Bildschirmfoto 2024-02-29 um 17 17 16](https://github.com/livingmydesign/hdstories/assets/159889907/bf3a8752-6218-4237-81fc-e85ded665a5c)

**Comment by livingmydesign** [comment]
@jansthh die Musik darf 1 Sekunde starten bevor das erste Wort fällt, da aktuell auch eine Begrüßung der ähnliches stattfindet. 

Alternativ: ein prägnanter bzw. einprägsamer Story-Jingle (fand den von der App von Ava so genial), der etwas lauter ist, bevor dann die Hintergrundmusik kommt, die dann leiser ist und nur noch als Unterlegung dient. 

verstehst du was ich meine? @jansthh

**Comment by jansthh** [comment]
Ah, okay. Dann müsste bitte auch bei jedem Story Stil Musik laufen. Aktuell läuft noch nur Musik beim Kleinen Prinzen, meine ich. Und vielleicht kann man das Delay zumindest noch etwas verzögern. Die Idee ist aber schön.

Das mit dem Jingle hatte ich ja schon mal getestet. Habe nichts gutes gefunden. Aber ich schaue nochmal zb hier https://www.storyblocks.com/ . Der muss dann auch wirklich gut sein und darf niemals nerven

**Comment by livingmydesign** [comment]
ja, am besten ein ruhiges tiefes geräusch, oder.

wie eine Seite in einem großen Buch, die umgeblättert wird vom Nikolaus. :D @jansthh

**Comment by livingmydesign** [comment]
erstmal zu schließen.

jede story hat jetzt eine eigene Musik. @jansthh 
jingle wäre cool irgendwann zwecks marke
