### ISSUE TITLE
IOS Share Button

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#80]
- in iOS (iPhone und iPad) auf der Story Share Seite passiert nichts beim drücken des "Storylink kopieren" Buttons

- egal, in welchem Browser

- ansonsten könnten wir auch überlegen, den Button für was anderes zu nutzen, weil die Story Seite ja mittlerweile schon der Link ist und sie das über die Systemtasten des Devices selber teilen können

- was meinst du?

**Comment by livingmydesign** [comment]
Ich muss mir das erstmal ansehen.

hab eigentlich auch selbst ein altes iPhone rumliegen für Testzwecke das ich bisher noch nicht eingesetzt hab.

wenn es sich nicht fixen lässt, ja. @jansthh

**Comment by livingmydesign** [comment]
Ok. 

Schritt 1:
im Text darunter Menschen informieren, dass sie die Story direkt teilen können über den Browser.

Schritt 2: 
eine neue Funktion für den Button finden.
"Spenden"? :D

@jansthh

**Comment by jansthh** [comment]
Danke. Habe auch hier den Footer-Text ergänzt.

Idee: Ein Feedback-Formular einbinden in der Anfangsphase? Und im Feedback-Formular einen Kofi-Spendenaufruf einbauen? Was meinst du?

**Comment by livingmydesign** [comment]
Tolle Idee!

Den Spendenaufruf würde ich entweder als Link auf der finalen Danke-Seite einbauen, 
oder aber direkt automatisch nach dem Absenden des Feedbacks auf Kofi umleiten.

Die Umsetzung sollte schnell gehen. 
Der Einfachheit halber einfach ein Google-Form würde ich sagen.

Ich nehme dir gerne alles ab, was nicht konzeptionell ist.
@jansthh

**Comment by livingmydesign** [comment]
@jansthh sollte ja nun gelöst sein.
