### ISSUE TITLE
Storylänge

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#81]
- Ich finde, wir sollten die Premium Stories auf keinen Fall unter 3 Minuten, sondern eher 3-4 Min. lang werden lassen

- magst du das einmal einstellen, so dass ich es testen kann, um ein Gefühl zu bekommen?

- wie könnten eigentlich deutlich längere Stories zukünftig fkt? Mehrere Teile einer Geschichte generieren lassen? ZB Starte Teil 1 mit Prompt 1 und dann Teil 2 mit Prompt 2 etc?

**Comment by livingmydesign** [comment]
@jansthh hab für Trial jetzt 60-100 Worte und für Credit-Stories für den nächsten Test 200-300 Worte eingestellt.

Ich denke, dass die  Stories u.U. auch zu lang werden könnten bei nur 1 Bild mit 1 Szene. 
Für mehrere Szenen mit konsistentem Charakter bräuchten wir noch AI-Support und Entwicklungszeit.
Eine gute Balance wäre vmtl. entscheidend.

würde da eher auf mehr persönliche Inputs statt Länge setzen um die Qualität statt die Quantität zu erhöhen.

**Comment by jansthh** [comment]
Ich verstehe deinen Punkt mit den Inputs und mehr Dynamik. Aber das ist ja Zukunftsmusik.

Mir geht es darum, was wir jetzt schon easy ändern könnten und die Geschichte schon auch qualitativ verbessern würde. Und einen merklichen Unterschied macht.

Das Argument mit dem Bild sehe ich gar nicht so, weil es ja auch vor allem ein Audio ist. Wenn wir später mal die Geschichte wirklich auch visuell erzählen können, super. Aber das wird vielleicht noch länger nicht gehen.

Lass uns doch in der Mitte treffen und die Wortlänge so einstellen, dass es bei den Premium immer mindestens 3 Min. sind. Also 300-400 Wörter? :)

Ich möchte es mindestens mal testen die Tage, um ein Gefühl dafür zu bekommen.

**Comment by livingmydesign** [comment]
@jansthh 300-400 it is now.

bitte nur im Auge behalten, dass wir uns ein paar Upgrade-Joker auch behalten sollten um preisliche Anpassungen nach oben zu fair zu gestalten.

**Comment by jansthh** [comment]
Wie könnte das denn mit richtig langen (teuren) Stories fkt. später? Nochmal zu dem Punkt von oben:

- wie könnten eigentlich deutlich längere Stories zukünftig fkt? Mehrere Teile einer Geschichte generieren lassen? ZB Starte Teil 1 mit Prompt 1 und dann Teil 2 mit Prompt 2 etc?

Oder einen GPT dafür bauen?
