### ISSUE TITLE
E-Mail Adressen: wo landen sie?

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#82]
- könnten die Namen+Mail-Adressen der User automatisch in einem speziellen flodesk abgelegt werden? Oder halt in SendGrid? 

- fürs Marketing müssen die ja am besten gleich gut strukturiert automatisiert abgelegen

- sendgrid ist zwar nicht so schön, aber damit könnten wir wahrscheinlich auch automatisierte dynamische Templates erstellen, die zB Usern zum Geb gratulieren

**Comment by livingmydesign** [comment]
Wäre beides möglich, via API. @jansthh 

Automatisierungen und  dynamische Inhalte via Sendgrid.
+ Leute kennen den Style dann eh auch schon.

Bist herzlich eingeladen, bei Gelegenheit ein "Alles Gute zum Geburtstag"-SendGrid Template zu bauen bei dem eine "Geburtstagsgeschichte" automatisch generiert erstellt und verschickt werden soll.

**Comment by jansthh** [comment]
Okay, muss nochmal überlegen, ob wir sie vielleicht bei flodesk + sendgrind eintragen und dann sendgrid für die dynamischen Automatisierungen nutzen und flodesk für die visuelleren Ankündigungen. 

So oder so sollten wir die Mail-Adressen dann bei Sendgrid sammeln. Wie übertragen wir die Spender Mails am besten in Sendgrid?

Okay, ich lege mir mal ein Issue an fürs B-Day-Template :)

**Comment by livingmydesign** [comment]
@jansthh SpenderEmails:

bei Sendgrid müssen eigentlich keine Emailadressen direkt gesammelt werden.  Sendgrid dienst uns eher als durchlauf-katalysator. es werden einfach emails direkt aus make.com oder aus der app heraus verschickt.

ansonsten ja. 
Datenbank-Extrahierung via CSV und re-import in den Email-Verteiler

**Comment by jansthh** [comment]
Ach, stimmt. Habe eben nochmal flodesk überprüft und dort gesehen, dass ich damals extra die Domain verified hatte.

**Dann wäre SUPER wichtig, dass wir alle bisherigen (Donor) und zukünftigen automatisch bei flodesk per API hinzufügen.** 

Hatte damals auch schon ein Segment angelegt "HD Stories Users"

Kannst du des so einrichten, dass alle E-Mails dort landen? So dass ich damit und von dort aus Kampagnen starten kann?
