### ISSUE TITLE
Story Text oben leicht abgeschnitten (seit Scrolling)

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#83]
- seit der Scroll Funktion auf der Story Seite wird der Text oben leicht abgeschnitten, wenn eingeblendet (auf allen Devices), siehe Screenshot

- muss sicher nur etwas Padding oben hinzugefügt werden

![Bildschirmfoto 2024-03-01 um 11 28 43](https://github.com/livingmydesign/hdstories/assets/159889907/06f01f00-a290-4651-aeb0-44dca03757ce)

**Comment by livingmydesign** [comment]
ja, korrekt - wird angepasst.

**Comment by livingmydesign** [comment]
sollte nun erledigt sein. @jansthh 

ticket wird geschlossen.
