### ISSUE TITLE
Story für mich Daten

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#85]
- habe ja heute diese coole Story für einen Manifestor gemacht, der auch Jan heißt: https://hdstories.app/share/AFVhu2

- als ich mit meinem Papa essen war, habe ich ihm die App gezeigt und der Einfachheit halber für mich (eingeloggt mit jansthh@gmail.com) erstellt

- da kam diese heraus und er spricht von einem Manifestor: https://hdstories.app/share/fYwlUq

- in einem weiteren Test von eben hat er wieder das neue Jan-Manifestor Chart zu verwendet: https://hdstories.app/share/wvbfob

- kann es sein, dass er nur wegen des Vornamens durcheinander war und nun die zuletzt erstellte Story als Geb-Daten Grundlage genommen hat?

**Comment by livingmydesign** [comment]
sehe ich mir näher an morgen

**Comment by livingmydesign** [comment]
Sollte nun behoben sein @jansthh für alle weiteren Stories für dich oder andere.
Bitte testen @jansthh

**Comment by jansthh** [comment]
Danke dir. Kann es erst wieder testen, wenn der "20%-Bug" behoben ist 🙏🏻 (https://github.com/livingmydesign/hdstories/issues/95)

**Comment by livingmydesign** [comment]
ist soweit behoben. @jansthh
