### ISSUE TITLE
HD Begriffe Wording

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#88]
- in einigen Stories kommt es noch zu richtig doofen Übersetzungen, Wordings und Aussprachen
- zB nennt er die Mentale Autorität meistens "none" und spricht sie deutsch "noonä" aus 😬😅
- auch bei Profilen etc kommt es oft zu ganz umständlichen Aussprachen

Was brauchst du alles genau von mir, damit ich das einmal alles angehen kann und wir in den Prompt einbauen? 

Ich weiß aus Erfahrung, dass es nicht reicht, wenn man ihm sagt: "Schreibe alle 12 Profile auf deutsch aus"

Meistens klappt nicht mal das konstant: schreibe alle Zahlen als Wort aus

**Comment by livingmydesign** [comment]
@jansthh war das auch die letzten Tage? falls ja, bitte schick mir ein Beispiel. Ich hatte am Wochenende dazu einen Bug behoben, der das Englische noch vorbeigeschleust hat.

**Comment by jansthh** [comment]
Ein Beispiel vom 1.3. (Sophie, 5/1 Mentale Projektorin):

https://hdstories.app/mystory/o1mNMH

Der letzte Absatz (siehe Screenshot)

![Bildschirmfoto 2024-03-06 um 12 26 29](https://github.com/livingmydesign/hdstories/assets/159889907/511c0747-1494-4091-a51d-46da7a79f89b)

**Comment by livingmydesign** [comment]
Done, ist nun behoben. 
War noch "Mental" statt "None" als Filter drinnen. @jansthh
