### ISSUE TITLE
Story Start + Musiklautstärke

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#90]
- bitte nach dem Klicken auf Start von 4 Sekunden auf 3 gehen.
- bitte die Musik nach wie vor wieder etwas lauter – man hört sie fast gar nicht

**Comment by livingmydesign** [comment]
Hum. Sacral No zu nochmal kürzen gerade jetzt.
Tatsächlich sind es gerade 3 Sekunden hier bei dem Pause-file. und ich empfinde es auch überhaupt nicht zu lange und könnte eigentlich auch länger lauschen bis die Geschichte startet. + Wenn man nichts erwartet, ists denke ich subjektiv ein anderes Erlebnis, wo auch das Vorspiel wichtiger ist

Also ja: bevor ich wieder die Musik anpasse, das ist leider etwas umständlich und zeitaufwendig jedes mal, wäre es vl. ganz gut, ein Optimum künstlich zu entwerfen als Prototyp, wo dann alles passt.

Beispiel: Die Musik kann lauter anfangen und dann wieder leiser werden, wenn deine Stimme anfängt.

Bitte spür mal rein und wenn du kannst, schick mir ein Beispiel, das für dich perfekt abgestimmt ist.
Will diese Arbeit möglichst nur noch einmal machen müssen der Effizienz wegen.
@jansthh

**Comment by jansthh** [comment]
Tut mir Leid, dass es so aufwändig ist. Das war mir nicht bewusst. Wenn du zukünftig solche Erweiterungen baust, teile mir vielleicht am besten mit, wie viel Aufwand Anpassungen für dich bedeuten würden.

Das letzte, was ich will ist, dass bei dir Frust entsteht wegen Anfragen und Aufgaben, auf die du keinen Bock hast 🙏🏻

Wir lassen das jetzt gern komplett so. Nur 2 Dinge:

- aktuell ertönt ein Störgeräusch mit der Musik, bevor meine Stimme startet. Offenbar bei jeder Story. Bsp: https://hdstories.app/mystory/sZI7EA

- bitte die Musik einfach nur insgesamt ein paar Prozent lauter, so dass man sie schon deutlicher hört. Die Stücke sind ja alle so dezent, dass sie nicht stören. Hier ein Beispiel aus meinen Reels mit einem unserer MP3s - vielleicht etwas leiser, weil du es glaube ich leiser magst: https://www.instagram.com/reel/Cn6sChIoCzJ/?igsh=MWtoOTNtNHM2cWk3MQ==

Hoffe, das reicht als Referenz. Ich stelle die Hintergrundmusik meistens zwischen 5-11% Lautstärke ein. Je nachdem, wie dominant das Stück ist.

Und dann können wir das Ticket schließen. Danke für deine Geduld ❤️

**Comment by livingmydesign** [comment]
Sound-Check. Test-Test..  123.

https://magic.hdstories.app/music/test01.MP3

wie ist das für dich? passt es vom Audio-Fade-In-Volume-Level?
@jansthh

**Comment by jansthh** [comment]
Perfekt! Danke :)

**Comment by livingmydesign** [comment]
gut. sind jetzt auch alle 5 ausgetauscht im system. darf jetzt gerne auch mal so bleiben fürs erste  :)
@jansthh
