### ISSUE TITLE
Jans Story falsche Geb-Daten

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#91]
- seit ich für den 1/3 Manifestor Jan (03.06.1999, 6:19 Uhr) eine Story erstellt habe, macht er jedes Mal bei "weitere für mich" eine Story für den 1/3 Manifestor statt für mich
- hatte den Verdacht geäußert, dass er durch den selben Vornamen irritiert sein könnte? Ansonsten macht es ja keinen Sinn und kam bisher nie vor

**Comment by livingmydesign** [comment]
ja, schaue ich mir mal näher an, wie sowas entsteht

**Comment by livingmydesign** [comment]
Fehler wurde gefunden und der Bug sollte nun behoben sein.
@jansthh
