### ISSUE TITLE
USA Orte nur bis Port Orange

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#92]
- ich wollte gerade ein Chart für Steve Jobs anlegen
- und konnte bei Land "United States" nicht "San Francisco" auswählen, weil die Ortauswahl auch nur bis "Port Orange" ging

![Bildschirmfoto 2024-03-04 um 14 18 48](https://github.com/livingmydesign/hdstories/assets/159889907/451ef033-fbb4-4c0a-bbfa-001475a2798b)

**Comment by livingmydesign** [comment]
interessant was du da gefunden hast. mal sehen

**Comment by livingmydesign** [comment]
![Screenshot 2024-04-13 at 07 02 18](https://github.com/livingmydesign/hdstories/assets/93006467/cf72b020-1a97-4472-9c6a-8977dce4f3c9)

war ein Datenbank Select Limit von 1000 Einträgen.
Hab es entsprechend angepasst auf 1500 Einträge und somit behoben.

@jansthh
