### ISSUE TITLE
Story auf anderem Gerät

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#93]
- Wollte gerade eine Story erzeugen
- hing zu lange bei 20%
- E-Mail kam auch nicht
- nach Reload neuer Versuch
- und dann der Screen im Anhang

Frage: Was kann ich dann tun als Kunde? Offenbar ist er hängen geblieben

Ich persönlich kann nun zB keine Stories mehr erzeugen, solange er noch denkt, dass gerade eine für mich erstellt wird 🤬😘

![image](https://github.com/livingmydesign/hdstories/assets/159889907/cb8f6ff3-2718-4848-8c2e-ba651c176a97)

**Comment by livingmydesign** [comment]
cool, das erste mal dass ich diesen Screen sehe. 
Wollte dieses Feature eh noch testen. 

soll eben verhindern, dass man mit 1 Credit auf mehreren Geräten gleichzeitig Stories erzeugt und so das System aushebelt. 

schau ich mir an, warum es nicht die Sperrung nach dem Abbruch entfernt hat. @jansthh

**Comment by livingmydesign** [comment]
Ok, in diesem Fall wurde die Story im Hintergrund fertig generiert und wäre auch im letzten Schritt abgeschickt worden wenn die App nicht vorzeitig verlassen worden wäre. 

@jansthh Was heißt: Hing zu lange bei 20%? > 5min? 10min?
In diesem Schritt generiert GPT die Geschichte. bei etwa 400 Worten kann es mitunter auch hier etwas dauern.
Das wäre die Geschichte gewesen, die er generiert hätte (tatsächlich in diesem Fall 500 Worte):

In einer Welt, nicht unähnlich der, welche der kleine Prinz bereiste, lebte ein junger Mann namens Noah. Er war ein Träumer und Denker, jemand, der stets nach Bedeutung in den Sternen und Geflüster im Wind suchte. Noah fühlte sich oft wie ein stiller Beobachter, der darauf wartete, in das Geschehen um ihn herum eingeladen zu werden. Er war wie ein Rätsel, im Nadir der Nacht versteckt, und nur jene, die das Wissen hatten, konnten seine wahre Essenz enthüllen.

Eines Nachts, während Noah alleine saß und den funkelnden Punkt am Himmel betrachtete, der sein Freund, der kleine Prinz, sein könnte, fühlte er eine plötzliche Gewissheit in seinem Inneren. Es war so, als hätte seine innere Stimme, leise und doch unmissverständlich, ihm geraten, eine Reise zu beginnen. Er staunte, "Ist das die Klarheit, die mich leitet?"

Mit der Demut eines Forschers und der Beharrlichkeit eines Märtyrers machte sich Noah auf den Weg. Die Welt hielt unzählige Geheimnisse für ihn bereit, und mit jeder Lektion, jedem Schicksalsschlag, sogar mit jedem Irrtum, fand er tieferen Sinn und Erkenntnis. "Nur durch Erfahrungen," murmelte er für sich, "kann man wahrhaft verstehen."

Er traf auf Gestalten und Charaktere, so vielfältig und bunt wie die Planeten, die der kleine Prinz besucht hatte. Er bot Hilfe an, jedoch ohne jene aufdringlichen Erwartungen – die Aufforderung war es, die ihm Freude bereitete. Menschen begannen, seine Einzigartigkeit zu sehen und schätzten sein Urteilsvermögen. "Höre uns zu und führe uns," sagten sie hoffnungsvoll, "deine Einsichten sind wie Leuchtfeuer im Dunkeln."

Obwohl ihn die Anerkennung wärmte, wurde Noah nicht von ihr verführt. "Wer versteht," sagte er leise, "dass das Licht, welches ich biete, von innen kommt und nicht von den Sternen aus der Ferne?" Er wusste, es war seine innewohnende Intuition, seine Milz-Autorität, die ihn sicher durch das Labyrinth des Lebens führte.

Und so, in Momenten der Stille, wenn Verwirrung oder Bedenken seinen Geist umwoben, lauschte Noah der Stimme tief in ihm. Es war ein subtiles Zittern, ein spontanes Wissen, das keine Worte benötigte. "Ich verstehe dich," sagte er ergriffen und bejahte die stumme Weisheit seiner eigenen Natur.

Dann kam der Tag, an dem Noah eine Entscheidung von großer Tragweite treffen musste. Die Menschen warteten auf seine Worte, in der Hoffnung, dass er sie durch eine Zeit der Dunkelheit führen würde. Noah schloss die Augen und atmete tief ein. ... In der Stille fand er seine Antwort, die weder aus Angst noch aus Erwartungen getrieben war. "Wir werden diesen Weg gehen," verkündete er mit der Ruhe eines Sehers.

Der Weg war nicht einfach, und er forderte seinen Tribut von Noah. Doch durch jeden Sturz lernte er mehr, durch jede Prüfung wurde er stärker. Und mit jeder Bestätigung wusste er: er war auf seinem richten Pfad.

Er blickte in den Nachthimmel, zu den Sternen, zu seinem Freund, und flüsterte ihm zu, "Ich habe meinen Platz gefunden, und in meinem Herzen weiß ich, dass es richtig ist." In diesem Augenblick war Noah wie der kleine Prinz – fern seiner Heimatwelt und doch verbunden mit den zentralen Wahrheiten des Universums.
-----

Hab jetzt einen weiteren Fail-Safe eingebaut, dass er den Lock auch bei ungeduldigeren Menschen wieder freigibt nach erfolgreich erzeugter Geschichte und App-Reload.

Wie gesagt: Lass uns besser überlegen, mit was die Wartezeit gefüllt werden kann / soll.
Und/Oder wie die Qualität bei relativ kurzen Stories erhöht werden könnte.

ticket closed.

**Comment by jansthh** [comment]
Danke 🙏🏻

"zu lange" hieß: auch nach Stunden hatte ich keine Mail mit der Story (bis jetzt auch noch nicht) und konnte keine neue generieren. Ich habe immer nur die o.g. Meldung erhalten. 

Seit deiner Telegram Nachricht, erst wieder zu testen, wenn du mir das GO gibst, habe ich es nicht mehr probiert

**Comment by livingmydesign** [comment]
hm. wie gesagt, emails werden aktuell nur verschickt, wenn man die App im Lade-Prozess nicht verlässt.

der Hintergrund: die Versand der Stories wird aktuell von der App direkt getriggert wenn die Story fertig gestellt ist.
Eben auch mit dem Ziel, immer mehr Prozesse direkt in der App abzubilden, statt sie auf Make.com auszulagern (Kostenfaktor)

Deshalb auch hier:
Ladezeiten gezielt bespielen mit Infos und nutzen mit dem Hinweis:
"Bitte schließe diese App nicht, wenn du eine Story-Email erhalten möchtest nach der Erstellung."

@jansthh

**Comment by jansthh** [comment]
Danke dir. Habe mal den Footer Text angepasst dahingehend. 

Das bestehende Problem ist ja aktuell, dass es einfach nicht weitergeht nach 20%. Auch nicht bei geöffnetem Fenster.
