### ISSUE TITLE
Sternentaler kaufen

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#94]
- generell ist es perspektivisch glaube ich clever, wenn wir die Käufe der Kunden immer eher in Relation mit Credits/Sternentaler bringen

- wie bei vielen Games das auch gemacht wird

- alle in App Käufe geschehen dann mit Sternentalern

- außerhalb kauft man immer nur Guthaben mit EUR

- eine normale Story zB = 1 Sternentaler
- eine Story mit deinen Themen = 2 Sternentaler
- eine Geb Story = 3 Sternentaler
- etc

**Comment by livingmydesign** [comment]
@jansthh Ja, kein Problem, solange:

Es immer nur uns als Sterntaler (finde ja, das "en" passt weniger gut, in der übergabe von so einem (singular) [Sterntaler](https://www.amazon.de/Die-Sterntaler-M%C3%A4rchen-Br%C3%BCder-Grimm/dp/3473303194)) - Bank und den Sterntaler - Konsumenten gibt. Kein Verschenken oder Handeln von Talern mit anderen. 
Nur Kaufen und Ausgeben ohne Verfallsdatum oder Ähnlichem wo dem einzelnen Taler irgendwelche extra-attribute oder serien-nummern zugewiesen werden müssten.

**Comment by livingmydesign** [comment]
![61L6L1ONQ9L _SY466_](https://github.com/livingmydesign/hdstories/assets/93006467/05d981d9-b55d-4606-8a10-8df1558513f2)
