### ISSUE TITLE
Story steckt bei 20% fest

### ISSUE THREAD

**Issue by jansthh** [livingmydesign/hdstories#95]
- Ich lege den Bug jetzt nochmal als extra issue an

- habe soeben nach deiner Freigabe den ersten Test wieder angestoßen mit einer Story für Noah (geboren 25.12.2017)

- wie beim letzten Mal hängt er schon seit über 5 Min. Stand jetzt bei 20% fest (Load Screens)

- habe weder auf Reload noch auf sonst was gedrückt

- eine E-Mail mit der Story (mit der letzten auch noch nicht) habe ich auch nicht erhalten

- das gab es noch nie - hatte ja auch schon längere Stories erstellt, die nie bei diesem Schritt stehenblieben 

🙏🏻

**Comment by jansthh** [comment]
Update: habe jetzt nochmal die Seite aufgerufen und auf refresh geklickt. Jetzt bin ich wieder bei der Storyauswahl gelandet. 

Eine Mail habe ich nicht bekommen mit der Story. 

Ich warte erstmal ab, bis du dir das angesehen hast 🙏🏻

**Comment by livingmydesign** [comment]
Ok.

Ich baue das ganze jetzt so um, dass sich der Lade-Prozess komplett von Außen steuern lässt.
Inkl genauer Prozentangaben, aktuellen Ladebildern und aktuellen Ladetexten.

So haben die komplette Kontrolle über das, was die Leute während das Ladens sehen, ohne dass wir dafür jedes Mal die App neu ausrollen müssen. Besonders, wenn du Werbung einbauen möchtest.  @jansthh 

irgendwann vl. sogar mit klick-able Werbecontent oder Video, etc.

**Comment by jansthh** [comment]
Danke, das sind alles tolle Ideen! :)) 

mir geht es aber ausschließlich darum, dass es wieder funktioniert und wir am besten herausfinden, warum es gerade nicht fkt. 🙏🏻

alles steht und fällt bei der App damit, ob sie so zuverlässig wie möglich fkt. – sonst verlieren User schnell Vertrauen und nutzen sie nicht mehr GERADE bei einer Magic Machine

merke das auch beim Chart Rechner. am Anfang gab es ein paar Probleme mit der Zuverlässigkeit bei der Berechnung. Das hätte das Produkt komplett gekillt.

❤️

**Comment by jansthh** [comment]
PS: Habe jetzt deine Voice dazu gehört. Dahingehend macht das natürlich total Sinn. Danke für deinen Einsatz. Ich hoffe natürlich vor allem, dass der Bug damit auch gelöst wird. Konntest du den bei einem Test nicht nachstellen?

**Comment by livingmydesign** [comment]
yeye. :)

alles gut mein lieber, bis morgen ist das Ding startklar und highly improved.

**Comment by livingmydesign** [comment]
soweit behoben.
